
import type { FoodDBItem } from '@/types';

// This file contains the initial food data to be seeded into your Firestore database.
// You can add more food items to this array by following the same format.
// After adding data, go to the /nutrition page and click the "Seed Food Database" button.

export const foodDatabase: FoodDBItem[] = [
  // Proteins
  {
    food_id: 'chicken_breast_grilled_0',
    name: 'Chicken Breast (Grilled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 165,
    protein_g: 31,
    carbs_g: 0,
    fat_g: 3.6,
    fiber_g: 0,
    common_names: [ 'grilled chicken', 'chicken breast' ],
    unit_conversions: { '1 piece (120g)': 1.2, '1 oz': 0.28 }
  },
  {
    food_id: 'salmon_baked_0',
    name: 'Salmon (Baked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 206,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    common_names: ['baked salmon', 'salmon fillet'],
    unit_conversions: { '3 oz fillet': 0.85 }
  },
  {
    food_id: 'whole_egg_0',
    name: 'Egg (Large)',
    category: 'Protein',
    serving_size: '1 egg',
    calories: 72,
    protein_g: 6.3,
    carbs_g: 0.4,
    fat_g: 4.8,
    fiber_g: 0,
    common_names: [ 'egg', 'whole egg' ],
    unit_conversions: { '100g': 2 }
  },
  {
    food_id: 'tofu_firm_0',
    name: 'Tofu (Firm)',
    category: 'Protein',
    serving_size: '100g',
    calories: 76,
    protein_g: 8,
    carbs_g: 1.9,
    fat_g: 4.8,
    fiber_g: 1.9,
    common_names: ['bean curd'],
    unit_conversions: { '1 cup': 2.5 }
  },
  {
    food_id: 'lentils_cooked_0',
    name: 'Lentils (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 116,
    protein_g: 9,
    carbs_g: 20,
    fat_g: 0.4,
    fiber_g: 8,
    common_names: ['lentil soup base'],
    unit_conversions: { '1 cup': 1.98 }
  },
  {
    food_id: 'chickpeas_canned_0',
    name: 'Chickpeas (Canned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 139,
    protein_g: 8.9,
    carbs_g: 27.4,
    fat_g: 2.6,
    fiber_g: 7.6,
    common_names: ['garbanzo beans'],
    unit_conversions: { '1 cup': 2.4 }
  },
  {
    food_id: 'greek_yogurt_plain_0',
    name: 'Greek Yogurt (Plain, Non-fat)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 59,
    protein_g: 10,
    carbs_g: 3.6,
    fat_g: 0.4,
    fiber_g: 0,
    common_names: ['strained yogurt'],
    unit_conversions: { '1 cup': 2.24 }
  },
  {
    food_id: 'cottage_cheese_2_0',
    name: 'Cottage Cheese (2%)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 81,
    protein_g: 12.4,
    carbs_g: 4.1,
    fat_g: 2.3,
    fiber_g: 0,
    common_names: ['curds and whey'],
    unit_conversions: { '1 cup': 2.26 }
  },
  {
    food_id: 'tuna_canned_in_water_0',
    name: 'Tuna (Canned in Water)',
    category: 'Protein',
    serving_size: '100g',
    calories: 116,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 0.8,
    fiber_g: 0,
    common_names: ['canned tuna'],
    unit_conversions: { '1 can (5 oz)': 1.42 }
  },
  {
    food_id: 'whey_protein_powder_0',
    name: 'Whey Protein Powder',
    category: 'Supplements',
    serving_size: '1 scoop (30g)',
    calories: 120,
    protein_g: 24,
    carbs_g: 3,
    fat_g: 1,
    fiber_g: 1,
    common_names: ['protein shake'],
    unit_conversions: { '100g': 3.33 }
  },
  {
    food_id: 'shrimp_cooked_0',
    name: 'Shrimp (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 99,
    protein_g: 24,
    carbs_g: 0.2,
    fat_g: 0.3,
    fiber_g: 0,
    common_names: ['prawns'],
    unit_conversions: { '3 oz': 0.85 }
  },

  // Carbohydrates
  {
    food_id: 'white_rice_cooked_0',
    name: 'White Rice (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 130,
    protein_g: 2.4,
    carbs_g: 28,
    fat_g: 0.3,
    fiber_g: 0.4,
    common_names: [ 'white rice' ],
    unit_conversions: { '1 cup': 1.58 }
  },
  {
    food_id: 'brown_rice_cooked_0',
    name: 'Brown Rice (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 111,
    protein_g: 2.6,
    carbs_g: 23,
    fat_g: 0.9,
    fiber_g: 1.8,
    common_names: ['whole grain rice'],
    unit_conversions: { '1 cup': 1.95 }
  },
  {
    food_id: 'quinoa_cooked_0',
    name: 'Quinoa (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 120,
    protein_g: 4.4,
    carbs_g: 21,
    fat_g: 1.9,
    fiber_g: 2.8,
    common_names: [],
    unit_conversions: { '1 cup': 1.85 }
  },
  {
    food_id: 'oats_rolled_dry_0',
    name: 'Oats (Rolled, Dry)',
    category: 'Carb',
    serving_size: '100g',
    calories: 389,
    protein_g: 16.9,
    carbs_g: 66.3,
    fat_g: 6.9,
    fiber_g: 10.6,
    common_names: ['oatmeal'],
    unit_conversions: { '1 cup (81g)': 0.81 }
  },
  {
    food_id: 'whole_wheat_bread_0',
    name: 'Whole Wheat Bread',
    category: 'Carb',
    serving_size: '1 slice (32g)',
    calories: 81,
    protein_g: 3.9,
    carbs_g: 13.8,
    fat_g: 1.1,
    fiber_g: 1.9,
    common_names: ['brown bread'],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'sweet_potato_baked_0',
    name: 'Sweet Potato (Baked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 90,
    protein_g: 2,
    carbs_g: 21,
    fat_g: 0.2,
    fiber_g: 3.3,
    common_names: ['yams'],
    unit_conversions: { '1 medium (114g)': 1.14 }
  },
  {
    food_id: 'russet_potato_baked_0',
    name: 'Russet Potato (Baked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 93,
    protein_g: 2.5,
    carbs_g: 21.2,
    fat_g: 0.1,
    fiber_g: 2.2,
    common_names: ['white potato'],
    unit_conversions: { '1 medium (173g)': 1.73 }
  },
  {
    food_id: 'pasta_cooked_0',
    name: 'Pasta (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 131,
    protein_g: 5,
    carbs_g: 25,
    fat_g: 1.1,
    fiber_g: 1.8,
    common_names: ['spaghetti', 'macaroni'],
    unit_conversions: { '1 cup': 1.4 }
  },
  {
    food_id: 'sourdough_bread_0',
    name: 'Sourdough Bread',
    category: 'Carb',
    serving_size: '1 slice (32g)',
    calories: 90,
    protein_g: 3.8,
    carbs_g: 18.2,
    fat_g: 0.6,
    fiber_g: 0.9,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'bagel_plain_0',
    name: 'Bagel (Plain)',
    category: 'Carb',
    serving_size: '1 medium (99g)',
    calories: 250,
    protein_g: 10,
    carbs_g: 50,
    fat_g: 1.5,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 1.01 }
  },
  {
    food_id: 'corn_tortilla_0',
    name: 'Corn Tortilla',
    category: 'Carb',
    serving_size: '1 tortilla (24g)',
    calories: 52,
    protein_g: 1.4,
    carbs_g: 11,
    fat_g: 0.6,
    fiber_g: 1.3,
    common_names: [],
    unit_conversions: { '100g': 4.16 }
  },

  // Fats
  {
    food_id: 'avocado_0',
    name: 'Avocado',
    category: 'Fats',
    serving_size: '100g',
    calories: 160,
    protein_g: 2,
    carbs_g: 8.5,
    fat_g: 14.7,
    fiber_g: 6.7,
    common_names: [],
    unit_conversions: { '1 medium (200g)': 2 }
  },
  {
    food_id: 'olive_oil_0',
    name: 'Olive Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 119,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.5,
    fiber_g: 0,
    common_names: ['extra virgin olive oil'],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'almonds_raw_0',
    name: 'Almonds (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 579,
    protein_g: 21.1,
    carbs_g: 21.6,
    fat_g: 49.9,
    fiber_g: 12.5,
    common_names: ['raw almonds'],
    unit_conversions: { '1 oz (28g)': 0.28 }
  },
  {
    food_id: 'peanut_butter_smooth_0',
    name: 'Peanut Butter (Smooth)',
    category: 'Fats',
    serving_size: '2 tbsp (32g)',
    calories: 191,
    protein_g: 7.2,
    carbs_g: 7.1,
    fat_g: 16,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'walnuts_raw_0',
    name: 'Walnuts (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 654,
    protein_g: 15.2,
    carbs_g: 13.7,
    fat_g: 65.2,
    fiber_g: 6.7,
    common_names: [],
    unit_conversions: { '1 oz (28g)': 0.28 }
  },
  {
    food_id: 'chia_seeds_0',
    name: 'Chia Seeds',
    category: 'Fats',
    serving_size: '100g',
    calories: 486,
    protein_g: 16.5,
    carbs_g: 42.1,
    fat_g: 30.7,
    fiber_g: 34.4,
    common_names: [],
    unit_conversions: { '1 tbsp (12g)': 0.12 }
  },
  {
    food_id: 'cheddar_cheese_0',
    name: 'Cheddar Cheese',
    category: 'Fats',
    serving_size: '100g',
    calories: 404,
    protein_g: 25,
    carbs_g: 1.3,
    fat_g: 33,
    fiber_g: 0,
    common_names: ['cheddar'],
    unit_conversions: { '1 slice (28g)': 0.28 }
  },
  {
    food_id: 'cashews_raw_0',
    name: 'Cashews (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 553,
    protein_g: 18,
    carbs_g: 30,
    fat_g: 44,
    fiber_g: 3.3,
    common_names: [],
    unit_conversions: { '1 oz (28g)': 0.28 }
  },

  // Fruits
  {
    food_id: 'apple_0',
    name: 'Apple',
    category: 'Fruit',
    serving_size: '1 medium (182g)',
    calories: 95,
    protein_g: 0.5,
    carbs_g: 25,
    fat_g: 0.3,
    fiber_g: 4.4,
    common_names: ['gala apple', 'fuji apple'],
    unit_conversions: { '100g': 0.55 }
  },
  {
    food_id: 'banana_0',
    name: 'Banana',
    category: 'Fruit',
    serving_size: '1 medium (118g)',
    calories: 105,
    protein_g: 1.3,
    carbs_g: 27,
    fat_g: 0.4,
    fiber_g: 3.1,
    common_names: [],
    unit_conversions: { '100g': 0.85 }
  },
  {
    food_id: 'orange_0',
    name: 'Orange',
    category: 'Fruit',
    serving_size: '1 medium (131g)',
    calories: 62,
    protein_g: 1.2,
    carbs_g: 15.4,
    fat_g: 0.2,
    fiber_g: 3.1,
    common_names: ['navel orange'],
    unit_conversions: { '100g': 0.76 }
  },
  {
    food_id: 'strawberries_0',
    name: 'Strawberries',
    category: 'Fruit',
    serving_size: '100g',
    calories: 32,
    protein_g: 0.7,
    carbs_g: 7.7,
    fat_g: 0.3,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '1 cup': 1.52 }
  },
  {
    food_id: 'blueberries_0',
    name: 'Blueberries',
    category: 'Fruit',
    serving_size: '100g',
    calories: 57,
    protein_g: 0.7,
    carbs_g: 14.5,
    fat_g: 0.3,
    fiber_g: 2.4,
    common_names: [],
    unit_conversions: { '1 cup': 1.48 }
  },
  {
    food_id: 'grapes_0',
    name: 'Grapes',
    category: 'Fruit',
    serving_size: '100g',
    calories: 69,
    protein_g: 0.7,
    carbs_g: 18,
    fat_g: 0.2,
    fiber_g: 0.9,
    common_names: [],
    unit_conversions: { '1 cup': 1.51 }
  },
  {
    food_id: 'watermelon_0',
    name: 'Watermelon',
    category: 'Fruit',
    serving_size: '100g',
    calories: 30,
    protein_g: 0.6,
    carbs_g: 7.6,
    fat_g: 0.2,
    fiber_g: 0.4,
    common_names: [],
    unit_conversions: { '1 cup diced': 1.52 }
  },
  {
    food_id: 'pineapple_0',
    name: 'Pineapple',
    category: 'Fruit',
    serving_size: '100g',
    calories: 50,
    protein_g: 0.5,
    carbs_g: 13,
    fat_g: 0.1,
    fiber_g: 1.4,
    common_names: [],
    unit_conversions: { '1 cup chunks': 1.65 }
  },
  {
    food_id: 'mango_0',
    name: 'Mango',
    category: 'Fruit',
    serving_size: '100g',
    calories: 60,
    protein_g: 0.8,
    carbs_g: 15,
    fat_g: 0.4,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '1 cup sliced': 1.65 }
  },
  {
    food_id: 'raspberries_0',
    name: 'Raspberries',
    category: 'Fruit',
    serving_size: '100g',
    calories: 52,
    protein_g: 1.2,
    carbs_g: 12,
    fat_g: 0.7,
    fiber_g: 6.5,
    common_names: [],
    unit_conversions: { '1 cup': 1.23 }
  },

  // Vegetables
  {
    food_id: 'broccoli_steamed_0',
    name: 'Broccoli (Steamed)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 35,
    protein_g: 2.4,
    carbs_g: 7,
    fat_g: 0.4,
    fiber_g: 3.3,
    common_names: [ 'broccoli' ],
    unit_conversions: { '1 cup': 1.56 }
  },
  {
    food_id: 'spinach_raw_0',
    name: 'Spinach (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 23,
    protein_g: 2.9,
    carbs_g: 3.6,
    fat_g: 0.4,
    fiber_g: 2.2,
    common_names: [],
    unit_conversions: { '1 cup': 0.3 }
  },
  {
    food_id: 'carrots_raw_0',
    name: 'Carrots (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 41,
    protein_g: 0.9,
    carbs_g: 9.6,
    fat_g: 0.2,
    fiber_g: 2.8,
    common_names: [],
    unit_conversions: { '1 medium': 0.61 }
  },
  {
    food_id: 'bell_pepper_red_0',
    name: 'Bell Pepper (Red)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 31,
    protein_g: 1,
    carbs_g: 6,
    fat_g: 0.3,
    fiber_g: 2.1,
    common_names: ['red pepper', 'capsicum'],
    unit_conversions: { '1 medium': 1.19 }
  },
  {
    food_id: 'cucumber_0',
    name: 'Cucumber',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 15,
    protein_g: 0.7,
    carbs_g: 3.6,
    fat_g: 0.1,
    fiber_g: 0.5,
    common_names: [],
    unit_conversions: { '1 cup sliced': 1.04 }
  },
  {
    food_id: 'tomato_0',
    name: 'Tomato',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 18,
    protein_g: 0.9,
    carbs_g: 3.9,
    fat_g: 0.2,
    fiber_g: 1.2,
    common_names: [],
    unit_conversions: { '1 medium': 1.23 }
  },
  {
    food_id: 'lettuce_romaine_0',
    name: 'Lettuce (Romaine)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 17,
    protein_g: 1.2,
    carbs_g: 3.3,
    fat_g: 0.3,
    fiber_g: 2.1,
    common_names: ['romaine'],
    unit_conversions: { '1 cup shredded': 0.47 }
  },
  {
    food_id: 'onion_yellow_0',
    name: 'Onion (Yellow)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 40,
    protein_g: 1.1,
    carbs_g: 9.3,
    fat_g: 0.1,
    fiber_g: 1.7,
    common_names: ['onion'],
    unit_conversions: { '1 cup chopped': 1.6 }
  },
  {
    food_id: 'mushrooms_white_0',
    name: 'Mushrooms (White)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 22,
    protein_g: 3.1,
    carbs_g: 3.3,
    fat_g: 0.3,
    fiber_g: 1,
    common_names: ['button mushrooms'],
    unit_conversions: { '1 cup sliced': 0.96 }
  },
  {
    food_id: 'zucchini_0',
    name: 'Zucchini',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 17,
    protein_g: 1.2,
    carbs_g: 3.1,
    fat_g: 0.3,
    fiber_g: 1,
    common_names: ['courgette'],
    unit_conversions: { '1 cup sliced': 1.13 }
  },
  {
    food_id: 'garlic_0',
    name: 'Garlic',
    category: 'Vegetable',
    serving_size: '1 clove (3g)',
    calories: 5,
    protein_g: 0.2,
    carbs_g: 1,
    fat_g: 0,
    fiber_g: 0.1,
    common_names: [],
    unit_conversions: { '100g': 33.3 }
  },
  {
    food_id: 'kale_raw_0',
    name: 'Kale (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 49,
    protein_g: 4.3,
    carbs_g: 9,
    fat_g: 0.9,
    fiber_g: 3.6,
    common_names: [],
    unit_conversions: { '1 cup chopped': 0.67 }
  },
  {
    food_id: 'celery_raw_0',
    name: 'Celery (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 16,
    protein_g: 0.7,
    carbs_g: 3,
    fat_g: 0.2,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '1 cup chopped': 1.01 }
  },

  // Dairy & Alternatives
  {
    food_id: 'milk_whole_0',
    name: 'Milk (Whole, 3.25%)',
    category: 'Dairy',
    serving_size: '1 cup (244g)',
    calories: 149,
    protein_g: 7.7,
    carbs_g: 11.7,
    fat_g: 8,
    fiber_g: 0,
    common_names: ['whole milk'],
    unit_conversions: { '100g': 0.41 }
  },
  {
    food_id: 'milk_skim_0',
    name: 'Milk (Skim)',
    category: 'Dairy',
    serving_size: '1 cup (245g)',
    calories: 83,
    protein_g: 8.3,
    carbs_g: 12.2,
    fat_g: 0.2,
    fiber_g: 0,
    common_names: ['non-fat milk'],
    unit_conversions: { '100g': 0.408 }
  },
  {
    food_id: 'almond_milk_unsweetened_0',
    name: 'Almond Milk (Unsweetened)',
    category: 'Dairy',
    serving_size: '1 cup (240ml)',
    calories: 30,
    protein_g: 1,
    carbs_g: 1,
    fat_g: 2.5,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100ml': 0.416 }
  },
  {
    food_id: 'soy_milk_unsweetened_0',
    name: 'Soy Milk (Unsweetened)',
    category: 'Dairy',
    serving_size: '1 cup (240ml)',
    calories: 80,
    protein_g: 7,
    carbs_g: 4,
    fat_g: 4,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100ml': 0.416 }
  },
  {
    food_id: 'mozzarella_cheese_0',
    name: 'Mozzarella Cheese (Part-Skim)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 280,
    protein_g: 28,
    carbs_g: 3.1,
    fat_g: 17,
    fiber_g: 0,
    common_names: ['mozzarella'],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'butter_salted_0',
    name: 'Butter (Salted)',
    category: 'Dairy',
    serving_size: '1 tbsp (14g)',
    calories: 102,
    protein_g: 0.1,
    carbs_g: 0,
    fat_g: 11.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },

  // Beverages
  {
    food_id: 'coffee_black_0',
    name: 'Coffee (Black)',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 2,
    protein_g: 0.3,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    common_names: ['black coffee'],
    unit_conversions: {}
  },
  {
    food_id: 'green_tea_0',
    name: 'Green Tea (Unsweetened)',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 2,
    protein_g: 0.5,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'orange_juice_0',
    name: 'Orange Juice',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 112,
    protein_g: 1.7,
    carbs_g: 26,
    fat_g: 0.5,
    fiber_g: 0.7,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'apple_juice_0',
    name: 'Apple Juice',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 114,
    protein_g: 0.2,
    carbs_g: 28,
    fat_g: 0.3,
    fiber_g: 0.5,
    common_names: [],
    unit_conversions: {}
  },
  
  // Miscellaneous
  {
    food_id: 'honey_0',
    name: 'Honey',
    category: 'Misc',
    serving_size: '1 tbsp (21g)',
    calories: 64,
    protein_g: 0.1,
    carbs_g: 17.3,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 4.76 }
  },
  {
    food_id: 'dark_chocolate_70_85_0',
    name: 'Dark Chocolate (70-85%)',
    category: 'Misc',
    serving_size: '100g',
    calories: 598,
    protein_g: 7.8,
    carbs_g: 45.9,
    fat_g: 42.6,
    fiber_g: 10.9,
    common_names: [],
    unit_conversions: { '1 square (10g)': 0.1 }
  },
  {
    food_id: 'ketchup_0',
    name: 'Ketchup',
    category: 'Misc',
    serving_size: '1 tbsp (17g)',
    calories: 17,
    protein_g: 0.2,
    carbs_g: 4.5,
    fat_g: 0.1,
    fiber_g: 0.1,
    common_names: ['tomato sauce'],
    unit_conversions: { '100g': 5.88 }
  },
  {
    food_id: 'mustard_yellow_0',
    name: 'Mustard (Yellow)',
    category: 'Misc',
    serving_size: '1 tsp (5g)',
    calories: 3,
    protein_g: 0.2,
    carbs_g: 0.3,
    fat_g: 0.2,
    fiber_g: 0.2,
    common_names: [],
    unit_conversions: { '100g': 20 }
  },
  {
    food_id: 'mayonnaise_full_fat_0',
    name: 'Mayonnaise (Full Fat)',
    category: 'Misc',
    serving_size: '1 tbsp (14g)',
    calories: 99,
    protein_g: 0.1,
    carbs_g: 0.1,
    fat_g: 11,
    fiber_g: 0,
    common_names: ['mayo'],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'popcorn_air_popped_0',
    name: 'Popcorn (Air-Popped)',
    category: 'Snack',
    serving_size: '1 cup (8g)',
    calories: 31,
    protein_g: 1,
    carbs_g: 6.2,
    fat_g: 0.4,
    fiber_g: 1.2,
    common_names: [],
    unit_conversions: { '100g': 12.5 }
  },
  {
    food_id: 'rice_cakes_brown_rice_0',
    name: 'Rice Cakes (Brown Rice)',
    category: 'Snack',
    serving_size: '1 cake (9g)',
    calories: 35,
    protein_g: 0.7,
    carbs_g: 7.3,
    fat_g: 0.3,
    fiber_g: 0.3,
    common_names: [],
    unit_conversions: { '100g': 11.1 }
  },
  {
    food_id: 'white_bread_0',
    name: 'White Bread',
    category: 'Carb',
    serving_size: '1 slice (25g)',
    calories: 66,
    protein_g: 2.3,
    carbs_g: 12.3,
    fat_g: 0.8,
    fiber_g: 0.6,
    common_names: [],
    unit_conversions: { '100g': 4 }
  },
  {
    food_id: 'turkey_breast_roasted_0',
    name: 'Turkey Breast (Roasted)',
    category: 'Protein',
    serving_size: '100g',
    calories: 135,
    protein_g: 30,
    carbs_g: 0,
    fat_g: 0.7,
    fiber_g: 0,
    common_names: ['roast turkey'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'sirloin_steak_broiled_0',
    name: 'Top Sirloin Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 206,
    protein_g: 29,
    carbs_g: 0,
    fat_g: 9,
    fiber_g: 0,
    common_names: ['beef sirloin', 'top sirloin', 'steak'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'pork_chop_cooked_0',
    name: 'Pork Chop (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 231,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 medium': 1.5 }
  },
  {
    food_id: 'black_beans_cooked_0',
    name: 'Black Beans (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 132,
    protein_g: 8.9,
    carbs_g: 23.7,
    fat_g: 0.5,
    fiber_g: 8.7,
    common_names: [],
    unit_conversions: { '1 cup': 1.72 }
  },
  {
    food_id: 'edamame_shelled_cooked_0',
    name: 'Edamame (Shelled, Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 122,
    protein_g: 11,
    carbs_g: 10,
    fat_g: 5,
    fiber_g: 5,
    common_names: ['soybeans'],
    unit_conversions: { '1 cup': 1.55 }
  },
  {
    food_id: 'green_beans_cooked_0',
    name: 'Green Beans (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 35,
    protein_g: 1.8,
    carbs_g: 8,
    fat_g: 0.3,
    fiber_g: 3.2,
    common_names: [],
    unit_conversions: { '1 cup': 1.25 }
  },
  {
    food_id: 'asparagus_cooked_0',
    name: 'Asparagus (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 20,
    protein_g: 2.2,
    carbs_g: 3.9,
    fat_g: 0.1,
    fiber_g: 2.1,
    common_names: [],
    unit_conversions: { '1 cup': 1.8 }
  },
  {
    food_id: 'cauliflower_raw_0',
    name: 'Cauliflower (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 25,
    protein_g: 1.9,
    carbs_g: 5,
    fat_g: 0.3,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '1 cup': 1 }
  },
  {
    food_id: 'sweet_corn_cooked_0',
    name: 'Sweet Corn (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 86,
    protein_g: 3.2,
    carbs_g: 19,
    fat_g: 1.2,
    fiber_g: 2.7,
    common_names: ['corn on the cob'],
    unit_conversions: { '1 ear': 1.4 }
  },
  {
    food_id: 'peas_green_cooked_0',
    name: 'Peas (Green, Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 81,
    protein_g: 5.4,
    carbs_g: 14.5,
    fat_g: 0.4,
    fiber_g: 5.1,
    common_names: ['green peas'],
    unit_conversions: { '1 cup': 1.6 }
  },
  {
    food_id: 'peach_0',
    name: 'Peach',
    category: 'Fruit',
    serving_size: '1 medium (150g)',
    calories: 59,
    protein_g: 1.4,
    carbs_g: 15,
    fat_g: 0.4,
    fiber_g: 2.3,
    common_names: [],
    unit_conversions: { '100g': 0.66 }
  },
  {
    food_id: 'pear_0',
    name: 'Pear',
    category: 'Fruit',
    serving_size: '1 medium (178g)',
    calories: 101,
    protein_g: 0.6,
    carbs_g: 27,
    fat_g: 0.2,
    fiber_g: 5.5,
    common_names: [],
    unit_conversions: { '100g': 0.56 }
  },
  {
    food_id: 'cherries_sweet_0',
    name: 'Cherries (Sweet)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 63,
    protein_g: 1.1,
    carbs_g: 16,
    fat_g: 0.2,
    fiber_g: 2.1,
    common_names: [],
    unit_conversions: { '1 cup': 1.54 }
  },
  {
    food_id: 'kiwi_0',
    name: 'Kiwi',
    category: 'Fruit',
    serving_size: '1 medium (69g)',
    calories: 42,
    protein_g: 0.8,
    carbs_g: 10.1,
    fat_g: 0.4,
    fiber_g: 2.1,
    common_names: ['kiwifruit'],
    unit_conversions: { '100g': 1.45 }
  },
  {
    food_id: 'peanuts_raw_0',
    name: 'Peanuts (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 567,
    protein_g: 25.8,
    carbs_g: 16.1,
    fat_g: 49.2,
    fiber_g: 8.5,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'sunflower_seeds_0',
    name: 'Sunflower Seeds',
    category: 'Fats',
    serving_size: '100g',
    calories: 584,
    protein_g: 20.8,
    carbs_g: 20,
    fat_g: 51.5,
    fiber_g: 8.6,
    common_names: [],
    unit_conversions: { '1/4 cup': 0.3 }
  },
  {
    food_id: 'flax_seeds_ground_0',
    name: 'Flax Seeds (Ground)',
    category: 'Fats',
    serving_size: '1 tbsp (7g)',
    calories: 37,
    protein_g: 1.3,
    carbs_g: 2,
    fat_g: 3,
    fiber_g: 1.9,
    common_names: [],
    unit_conversions: { '100g': 14.3 }
  },
  {
    food_id: 'sesame_oil_0',
    name: 'Sesame Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.6,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'maple_syrup_0',
    name: 'Maple Syrup',
    category: 'Misc',
    serving_size: '1 tbsp (20g)',
    calories: 52,
    protein_g: 0,
    carbs_g: 13.4,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 5 }
  },
  {
    food_id: 'cod_baked_0',
    name: 'Cod (Baked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 82,
    protein_g: 18,
    carbs_g: 0,
    fat_g: 0.7,
    fiber_g: 0,
    common_names: ['baked cod', 'cod fillet'],
    unit_conversions: { '3 oz fillet': 0.85 }
  },
  {
    food_id: 'pork_sausage_cooked_0',
    name: 'Pork Sausage (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 334,
    protein_g: 19,
    carbs_g: 0.7,
    fat_g: 28,
    fiber_g: 0,
    common_names: ['sausage link'],
    unit_conversions: { '1 link (57g)': 0.57 }
  },
  {
    food_id: 'lamb_chop_cooked_0',
    name: 'Lamb Chop (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 282,
    protein_g: 25,
    carbs_g: 0,
    fat_g: 20,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 chop (113g)': 1.13 }
  },
  {
    food_id: 'scallops_cooked_0',
    name: 'Scallops (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 111,
    protein_g: 23,
    carbs_g: 0,
    fat_g: 1,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'turkey_bacon_cooked_0',
    name: 'Turkey Bacon (Cooked)',
    category: 'Protein',
    serving_size: '1 slice (15g)',
    calories: 30,
    protein_g: 3,
    carbs_g: 0.2,
    fat_g: 2,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 6.67 }
  },
  {
    food_id: 'plant_burger_patty_0',
    name: 'Plant-based Burger Patty',
    category: 'Protein',
    serving_size: '1 patty (113g)',
    calories: 250,
    protein_g: 20,
    carbs_g: 9,
    fat_g: 14,
    fiber_g: 2,
    common_names: ['veggie burger', 'impossible burger', 'beyond burger'],
    unit_conversions: { '100g': 0.88 }
  },
  {
    food_id: 'barley_cooked_0',
    name: 'Barley (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 123,
    protein_g: 2.3,
    carbs_g: 28.2,
    fat_g: 0.4,
    fiber_g: 3.8,
    common_names: [],
    unit_conversions: { '1 cup': 1.57 }
  },
  {
    food_id: 'couscous_cooked_0',
    name: 'Couscous (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 112,
    protein_g: 3.8,
    carbs_g: 23.2,
    fat_g: 0.2,
    fiber_g: 1.4,
    common_names: [],
    unit_conversions: { '1 cup': 1.57 }
  },
  {
    food_id: 'flour_tortilla_0',
    name: 'Flour Tortilla',
    category: 'Carb',
    serving_size: '1 medium (42g)',
    calories: 120,
    protein_g: 3,
    carbs_g: 20,
    fat_g: 3,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100g': 2.38 }
  },
  {
    food_id: 'pretzels_hard_0',
    name: 'Pretzels (Hard)',
    category: 'Snack',
    serving_size: '100g',
    calories: 380,
    protein_g: 10,
    carbs_g: 80,
    fat_g: 3,
    fiber_g: 3,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'granola_0',
    name: 'Granola',
    category: 'Carb',
    serving_size: '100g',
    calories: 471,
    protein_g: 10,
    carbs_g: 64,
    fat_g: 20,
    fiber_g: 9,
    common_names: [],
    unit_conversions: { '1 cup': 0.85 }
  },
  {
    food_id: 'waffle_plain_0',
    name: 'Waffle (Plain)',
    category: 'Carb',
    serving_size: '1 waffle (39g)',
    calories: 103,
    protein_g: 2.5,
    carbs_g: 17,
    fat_g: 3,
    fiber_g: 0.7,
    common_names: [],
    unit_conversions: { '100g': 2.56 }
  },
  {
    food_id: 'coconut_oil_0',
    name: 'Coconut Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 121,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'cream_cheese_0',
    name: 'Cream Cheese',
    category: 'Fats',
    serving_size: '1 tbsp (14.5g)',
    calories: 51,
    protein_g: 0.9,
    carbs_g: 0.8,
    fat_g: 5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 6.9 }
  },
  {
    food_id: 'feta_cheese_0',
    name: 'Feta Cheese',
    category: 'Fats',
    serving_size: '100g',
    calories: 264,
    protein_g: 14,
    carbs_g: 4.1,
    fat_g: 21,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'pecans_0',
    name: 'Pecans',
    category: 'Fats',
    serving_size: '100g',
    calories: 691,
    protein_g: 9.2,
    carbs_g: 13.9,
    fat_g: 72,
    fiber_g: 9.6,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'pistachios_0',
    name: 'Pistachios',
    category: 'Fats',
    serving_size: '100g',
    calories: 562,
    protein_g: 20,
    carbs_g: 28,
    fat_g: 45,
    fiber_g: 10,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'macadamia_nuts_0',
    name: 'Macadamia Nuts',
    category: 'Fats',
    serving_size: '100g',
    calories: 718,
    protein_g: 7.9,
    carbs_g: 13.8,
    fat_g: 76,
    fiber_g: 8.6,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'artichoke_hearts_cooked_0',
    name: 'Artichoke Hearts (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 53,
    protein_g: 2.9,
    carbs_g: 12,
    fat_g: 0.3,
    fiber_g: 5.7,
    common_names: [],
    unit_conversions: { '1 cup': 1.65 }
  },
  {
    food_id: 'brussels_sprouts_cooked_0',
    name: 'Brussels Sprouts (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 36,
    protein_g: 2.6,
    carbs_g: 7.1,
    fat_g: 0.5,
    fiber_g: 2.6,
    common_names: [],
    unit_conversions: { '1 cup': 1.56 }
  },
  {
    food_id: 'beets_cooked_0',
    name: 'Beets (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 44,
    protein_g: 1.7,
    carbs_g: 10,
    fat_g: 0.2,
    fiber_g: 2,
    common_names: ['beetroot'],
    unit_conversions: { '1 cup': 1.7 }
  },
  {
    food_id: 'eggplant_cooked_0',
    name: 'Eggplant (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 35,
    protein_g: 0.8,
    carbs_g: 8.7,
    fat_g: 0.2,
    fiber_g: 2.5,
    common_names: ['aubergine'],
    unit_conversions: { '1 cup': 0.99 }
  },
  {
    food_id: 'okra_cooked_0',
    name: 'Okra (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 22,
    protein_g: 2,
    carbs_g: 4.5,
    fat_g: 0.2,
    fiber_g: 2.5,
    common_names: [],
    unit_conversions: { '1 cup': 1.6 }
  },
  {
    food_id: 'parsnip_cooked_0',
    name: 'Parsnip (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 71,
    protein_g: 1.3,
    carbs_g: 17.5,
    fat_g: 0.3,
    fiber_g: 4.8,
    common_names: [],
    unit_conversions: { '1 cup': 1.56 }
  },
  {
    food_id: 'radish_raw_0',
    name: 'Radish (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 16,
    protein_g: 0.7,
    carbs_g: 3.4,
    fat_g: 0.1,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '1 cup': 1.16 }
  },
  {
    food_id: 'turnip_cooked_0',
    name: 'Turnip (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 22,
    protein_g: 0.7,
    carbs_g: 5,
    fat_g: 0.1,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '1 cup': 1.56 }
  },
  {
    food_id: 'plum_0',
    name: 'Plum',
    category: 'Fruit',
    serving_size: '1 medium (66g)',
    calories: 30,
    protein_g: 0.5,
    carbs_g: 7.5,
    fat_g: 0.2,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100g': 1.51 }
  },
  {
    food_id: 'cantaloupe_0',
    name: 'Cantaloupe',
    category: 'Fruit',
    serving_size: '100g',
    calories: 34,
    protein_g: 0.8,
    carbs_g: 8.2,
    fat_g: 0.2,
    fiber_g: 0.9,
    common_names: ['rockmelon'],
    unit_conversions: { '1 cup': 1.6 }
  },
  {
    food_id: 'honeydew_melon_0',
    name: 'Honeydew Melon',
    category: 'Fruit',
    serving_size: '100g',
    calories: 36,
    protein_g: 0.5,
    carbs_g: 9.1,
    fat_g: 0.1,
    fiber_g: 0.8,
    common_names: [],
    unit_conversions: { '1 cup': 1.7 }
  },
  {
    food_id: 'grapefruit_0',
    name: 'Grapefruit',
    category: 'Fruit',
    serving_size: '1/2 medium (123g)',
    calories: 52,
    protein_g: 1,
    carbs_g: 13,
    fat_g: 0.2,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 0.81 }
  },
  {
    food_id: 'lemon_0',
    name: 'Lemon',
    category: 'Fruit',
    serving_size: '1 fruit (58g)',
    calories: 17,
    protein_g: 0.6,
    carbs_g: 5.4,
    fat_g: 0.2,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '100g': 1.72 }
  },
  {
    food_id: 'lime_0',
    name: 'Lime',
    category: 'Fruit',
    serving_size: '1 fruit (67g)',
    calories: 20,
    protein_g: 0.5,
    carbs_g: 7,
    fat_g: 0.1,
    fiber_g: 1.9,
    common_names: [],
    unit_conversions: { '100g': 1.49 }
  },
  {
    food_id: 'nectarine_0',
    name: 'Nectarine',
    category: 'Fruit',
    serving_size: '1 medium (142g)',
    calories: 62,
    protein_g: 1.5,
    carbs_g: 15,
    fat_g: 0.5,
    fiber_g: 2.4,
    common_names: [],
    unit_conversions: { '100g': 0.7 }
  },
  {
    food_id: 'pomegranate_seeds_0',
    name: 'Pomegranate Seeds',
    category: 'Fruit',
    serving_size: '100g',
    calories: 83,
    protein_g: 1.7,
    carbs_g: 18.7,
    fat_g: 1.2,
    fiber_g: 4,
    common_names: ['arils'],
    unit_conversions: { '1/2 cup': 0.87 }
  },
  {
    food_id: 'sour_cream_0',
    name: 'Sour Cream',
    category: 'Dairy',
    serving_size: '2 tbsp (30g)',
    calories: 59,
    protein_g: 0.7,
    carbs_g: 1.3,
    fat_g: 5.8,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 3.33 }
  },
  {
    food_id: 'oat_milk_0',
    name: 'Oat Milk',
    category: 'Dairy',
    serving_size: '1 cup (240ml)',
    calories: 120,
    protein_g: 3,
    carbs_g: 16,
    fat_g: 5,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100ml': 0.416 }
  },
  {
    food_id: 'coconut_yogurt_0',
    name: 'Coconut Yogurt',
    category: 'Dairy',
    serving_size: '100g',
    calories: 121,
    protein_g: 1,
    carbs_g: 10,
    fat_g: 8,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 container (150g)': 1.5 }
  },
  {
    food_id: 'parmesan_cheese_grated_0',
    name: 'Parmesan Cheese (Grated)',
    category: 'Dairy',
    serving_size: '1 tbsp (5g)',
    calories: 22,
    protein_g: 1.9,
    carbs_g: 0.1,
    fat_g: 1.5,
    fiber_g: 0,
    common_names: ['parmigiano-reggiano'],
    unit_conversions: { '100g': 20 }
  },
  {
    food_id: 'hummus_0',
    name: 'Hummus',
    category: 'Snack',
    serving_size: '2 tbsp (30g)',
    calories: 70,
    protein_g: 2,
    carbs_g: 4,
    fat_g: 5,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 3.33 }
  },
  {
    food_id: 'salsa_0',
    name: 'Salsa',
    category: 'Misc',
    serving_size: '2 tbsp (30g)',
    calories: 10,
    protein_g: 0.5,
    carbs_g: 2,
    fat_g: 0,
    fiber_g: 0.5,
    common_names: ['pico de gallo'],
    unit_conversions: { '100g': 3.33 }
  },
  {
    food_id: 'tortilla_chips_0',
    name: 'Tortilla Chips',
    category: 'Snack',
    serving_size: '1 oz (28g)',
    calories: 140,
    protein_g: 2,
    carbs_g: 18,
    fat_g: 7,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'potato_chips_0',
    name: 'Potato Chips',
    category: 'Snack',
    serving_size: '1 oz (28g)',
    calories: 160,
    protein_g: 2,
    carbs_g: 15,
    fat_g: 10,
    fiber_g: 1,
    common_names: ['crisps'],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'granola_bar_0',
    name: 'Granola Bar',
    category: 'Snack',
    serving_size: '1 bar (28g)',
    calories: 120,
    protein_g: 2,
    carbs_g: 20,
    fat_g: 4,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'raisins_0',
    name: 'Raisins',
    category: 'Fruit',
    serving_size: '1/4 cup (40g)',
    calories: 120,
    protein_g: 1,
    carbs_g: 32,
    fat_g: 0.1,
    fiber_g: 1.5,
    common_names: [],
    unit_conversions: { '100g': 2.5 }
  },
  {
    food_id: 'balsamic_vinaigrette_0',
    name: 'Balsamic Vinaigrette',
    category: 'Misc',
    serving_size: '2 tbsp (30ml)',
    calories: 70,
    protein_g: 0,
    carbs_g: 3,
    fat_g: 7,
    fiber_g: 0,
    common_names: ['salad dressing'],
    unit_conversions: { '100ml': 3.33 }
  },
  {
    food_id: 'ranch_dressing_0',
    name: 'Ranch Dressing',
    category: 'Misc',
    serving_size: '2 tbsp (30ml)',
    calories: 130,
    protein_g: 0.5,
    carbs_g: 2,
    fat_g: 14,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100ml': 3.33 }
  },
  {
    food_id: 'bacon_pork_cooked_0',
    name: 'Bacon (Pork, Cooked)',
    category: 'Protein',
    serving_size: '1 slice (8g)',
    calories: 43,
    protein_g: 3,
    carbs_g: 0.1,
    fat_g: 3.3,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 12.5 }
  },
  {
    food_id: 'halibut_cooked_0',
    name: 'Halibut (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 140,
    protein_g: 27,
    carbs_g: 0,
    fat_g: 3,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'tilapia_cooked_0',
    name: 'Tilapia (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 128,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 2.6,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'ground_turkey_93_7_0',
    name: 'Ground Turkey (93/7)',
    category: 'Protein',
    serving_size: '100g',
    calories: 176,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 10,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'casein_protein_powder_0',
    name: 'Casein Protein Powder',
    category: 'Supplements',
    serving_size: '1 scoop (32g)',
    calories: 120,
    protein_g: 24,
    carbs_g: 3,
    fat_g: 1,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'egg_whites_0',
    name: 'Egg Whites',
    category: 'Protein',
    serving_size: '100g',
    calories: 52,
    protein_g: 11,
    carbs_g: 0.7,
    fat_g: 0.2,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 large egg white': 0.33 }
  },
  {
    food_id: 'baguette_french_0',
    name: 'Baguette (French)',
    category: 'Carb',
    serving_size: '1 slice (25g)',
    calories: 70,
    protein_g: 2.5,
    carbs_g: 14,
    fat_g: 0.5,
    fiber_g: 0.6,
    common_names: [],
    unit_conversions: { '100g': 4 }
  },
  {
    food_id: 'buckwheat_cooked_0',
    name: 'Buckwheat (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 92,
    protein_g: 3.4,
    carbs_g: 20,
    fat_g: 0.6,
    fiber_g: 2.7,
    common_names: [],
    unit_conversions: { '1 cup': 1.68 }
  },
  {
    food_id: 'english_muffin_0',
    name: 'English Muffin',
    category: 'Carb',
    serving_size: '1 muffin (57g)',
    calories: 134,
    protein_g: 4.6,
    carbs_g: 26,
    fat_g: 1.1,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 1.75 }
  },
  {
    food_id: 'rye_bread_0',
    name: 'Rye Bread',
    category: 'Carb',
    serving_size: '1 slice (32g)',
    calories: 83,
    protein_g: 2.7,
    carbs_g: 15.5,
    fat_g: 1.1,
    fiber_g: 1.9,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'butter_unsalted_0',
    name: 'Butter (Unsalted)',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 102,
    protein_g: 0.1,
    carbs_g: 0,
    fat_g: 11.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'ghee_0',
    name: 'Ghee',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 123,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: ['clarified butter'],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'hemp_seeds_0',
    name: 'Hemp Seeds',
    category: 'Fats',
    serving_size: '3 tbsp (30g)',
    calories: 166,
    protein_g: 9.5,
    carbs_g: 2.6,
    fat_g: 14.6,
    fiber_g: 1.2,
    common_names: [],
    unit_conversions: { '100g': 3.33 }
  },
  {
    food_id: 'pumpkin_seeds_0',
    name: 'Pumpkin Seeds',
    category: 'Fats',
    serving_size: '1 oz (28g)',
    calories: 151,
    protein_g: 7,
    carbs_g: 5,
    fat_g: 13,
    fiber_g: 1.7,
    common_names: ['pepitas'],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'tahini_0',
    name: 'Tahini',
    category: 'Fats',
    serving_size: '1 tbsp (15g)',
    calories: 89,
    protein_g: 2.6,
    carbs_g: 3.2,
    fat_g: 8,
    fiber_g: 1.4,
    common_names: ['sesame paste'],
    unit_conversions: { '100g': 6.67 }
  },
  {
    food_id: 'arugula_0',
    name: 'Arugula',
    category: 'Vegetable',
    serving_size: '1 cup (20g)',
    calories: 5,
    protein_g: 0.5,
    carbs_g: 0.7,
    fat_g: 0.1,
    fiber_g: 0.3,
    common_names: ['rocket'],
    unit_conversions: { '100g': 5 }
  },
  {
    food_id: 'cabbage_cooked_0',
    name: 'Cabbage (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 23,
    protein_g: 1.1,
    carbs_g: 5.4,
    fat_g: 0.1,
    fiber_g: 1.9,
    common_names: [],
    unit_conversions: { '1 cup': 1.5 }
  },
  {
    food_id: 'collard_greens_cooked_0',
    name: 'Collard Greens (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 33,
    protein_g: 3,
    carbs_g: 5.6,
    fat_g: 0.7,
    fiber_g: 4,
    common_names: [],
    unit_conversions: { '1 cup': 1.9 }
  },
  {
    food_id: 'leeks_cooked_0',
    name: 'Leeks (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 31,
    protein_g: 0.8,
    carbs_g: 7.6,
    fat_g: 0.2,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '1 cup': 1.04 }
  },
  {
    food_id: 'watercress_0',
    name: 'Watercress',
    category: 'Vegetable',
    serving_size: '1 cup (34g)',
    calories: 4,
    protein_g: 0.8,
    carbs_g: 0.4,
    fat_g: 0,
    fiber_g: 0.2,
    common_names: [],
    unit_conversions: { '100g': 2.94 }
  },
  {
    food_id: 'apricot_0',
    name: 'Apricot',
    category: 'Fruit',
    serving_size: '1 fruit (35g)',
    calories: 17,
    protein_g: 0.5,
    carbs_g: 3.9,
    fat_g: 0.1,
    fiber_g: 0.7,
    common_names: [],
    unit_conversions: { '100g': 2.85 }
  },
  {
    food_id: 'blackberry_0',
    name: 'Blackberry',
    category: 'Fruit',
    serving_size: '100g',
    calories: 43,
    protein_g: 1.4,
    carbs_g: 10,
    fat_g: 0.5,
    fiber_g: 5.3,
    common_names: [],
    unit_conversions: { '1 cup': 1.44 }
  },
  {
    food_id: 'cranberries_dried_0',
    name: 'Cranberries (Dried)',
    category: 'Fruit',
    serving_size: '1/4 cup (40g)',
    calories: 123,
    protein_g: 0.1,
    carbs_g: 33,
    fat_g: 0.5,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 2.5 }
  },
  {
    food_id: 'dates_medjool_0',
    name: 'Dates (Medjool)',
    category: 'Fruit',
    serving_size: '1 date (24g)',
    calories: 66,
    protein_g: 0.4,
    carbs_g: 18,
    fat_g: 0,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '100g': 4.16 }
  },
  {
    food_id: 'figs_dried_0',
    name: 'Figs (Dried)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 249,
    protein_g: 3.3,
    carbs_g: 64,
    fat_g: 0.9,
    fiber_g: 9.8,
    common_names: [],
    unit_conversions: { '1 fig': 0.08 }
  },
  {
    food_id: 'guava_0',
    name: 'Guava',
    category: 'Fruit',
    serving_size: '1 fruit (55g)',
    calories: 37,
    protein_g: 1.4,
    carbs_g: 7.9,
    fat_g: 0.5,
    fiber_g: 3,
    common_names: [],
    unit_conversions: { '100g': 1.82 }
  },
  {
    food_id: 'papaya_0',
    name: 'Papaya',
    category: 'Fruit',
    serving_size: '1 cup (145g)',
    calories: 62,
    protein_g: 0.7,
    carbs_g: 15.7,
    fat_g: 0.4,
    fiber_g: 2.5,
    common_names: [],
    unit_conversions: { '100g': 0.69 }
  },
  {
    food_id: 'coconut_milk_canned_0',
    name: 'Coconut Milk (Canned)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 230,
    protein_g: 2.3,
    carbs_g: 5.5,
    fat_g: 24,
    fiber_g: 2.2,
    common_names: [],
    unit_conversions: { '1 cup': 2.4 }
  },
  {
    food_id: 'kefir_plain_0',
    name: 'Kefir (Plain)',
    category: 'Dairy',
    serving_size: '1 cup (243g)',
    calories: 104,
    protein_g: 9.2,
    carbs_g: 9,
    fat_g: 3.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 0.41 }
  },
  {
    food_id: 'provolone_cheese_0',
    name: 'Provolone Cheese',
    category: 'Dairy',
    serving_size: '1 slice (28g)',
    calories: 98,
    protein_g: 7.2,
    carbs_g: 0.6,
    fat_g: 7.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'swiss_cheese_0',
    name: 'Swiss Cheese',
    category: 'Dairy',
    serving_size: '1 slice (28g)',
    calories: 106,
    protein_g: 7.6,
    carbs_g: 1.5,
    fat_g: 7.8,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'agave_nectar_0',
    name: 'Agave Nectar',
    category: 'Misc',
    serving_size: '1 tbsp (21g)',
    calories: 64,
    protein_g: 0,
    carbs_g: 16,
    fat_g: 0.1,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 4.76 }
  },
  {
    food_id: 'bbq_sauce_0',
    name: 'BBQ Sauce',
    category: 'Misc',
    serving_size: '2 tbsp (34g)',
    calories: 60,
    protein_g: 0.3,
    carbs_g: 15,
    fat_g: 0.2,
    fiber_g: 0.3,
    common_names: [],
    unit_conversions: { '100g': 2.94 }
  },
  {
    food_id: 'hot_sauce_0',
    name: 'Hot Sauce',
    category: 'Misc',
    serving_size: '1 tsp (5g)',
    calories: 0,
    protein_g: 0.1,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0.1,
    common_names: ['tabasco', 'sriracha'],
    unit_conversions: { '100g': 20 }
  },
  {
    food_id: 'soy_sauce_0',
    name: 'Soy Sauce',
    category: 'Misc',
    serving_size: '1 tbsp (16g)',
    calories: 8,
    protein_g: 1.3,
    carbs_g: 1,
    fat_g: 0.1,
    fiber_g: 0.1,
    common_names: [],
    unit_conversions: { '100g': 6.25 }
  },
  {
    food_id: 'worcestershire_sauce_0',
    name: 'Worcestershire Sauce',
    category: 'Misc',
    serving_size: '1 tsp (5g)',
    calories: 4,
    protein_g: 0,
    carbs_g: 1,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 20 }
  },
  {
    food_id: 'pork_belly_cooked_1',
    name: 'Pork Belly (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 518,
    protein_g: 9,
    carbs_g: 0,
    fat_g: 53,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'beef_jerky_1',
    name: 'Beef Jerky',
    category: 'Snack',
    serving_size: '1 oz (28g)',
    calories: 116,
    protein_g: 9.4,
    carbs_g: 3.1,
    fat_g: 7.4,
    fiber_g: 0.5,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'anchovies_canned_in_oil_1',
    name: 'Anchovies (Canned in Oil)',
    category: 'Protein',
    serving_size: '100g',
    calories: 210,
    protein_g: 29,
    carbs_g: 0,
    fat_g: 9.7,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 can (56g)': 0.56 }
  },
  {
    food_id: 'bison_ground_cooked_1',
    name: 'Bison (Ground, Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 198,
    protein_g: 28,
    carbs_g: 0,
    fat_g: 8,
    fiber_g: 0,
    common_names: ['buffalo meat'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'chorizo_sausage_cooked_1',
    name: 'Chorizo Sausage (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 455,
    protein_g: 24,
    carbs_g: 1.9,
    fat_g: 38,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 link (85g)': 0.85 }
  },
  {
    food_id: 'crab_meat_canned_1',
    name: 'Crab Meat (Canned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 84,
    protein_g: 18,
    carbs_g: 0,
    fat_g: 1.1,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 cup': 1.15 }
  },
  {
    food_id: 'duck_meat_roasted_1',
    name: 'Duck Meat (Roasted)',
    category: 'Protein',
    serving_size: '100g',
    calories: 337,
    protein_g: 19,
    carbs_g: 0,
    fat_g: 28,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 cup': 1.4 }
  },
  {
    food_id: 'kidney_beans_canned_1',
    name: 'Kidney Beans (Canned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 127,
    protein_g: 8.7,
    carbs_g: 22.8,
    fat_g: 0.5,
    fiber_g: 6.4,
    common_names: [],
    unit_conversions: { '1 cup': 2.56 }
  },
  {
    food_id: 'lobster_cooked_1',
    name: 'Lobster (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 77,
    protein_g: 16,
    carbs_g: 0,
    fat_g: 0.9,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 cup': 1.45 }
  },
  {
    food_id: 'mackerel_cooked_1',
    name: 'Mackerel (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 262,
    protein_g: 24,
    carbs_g: 0,
    fat_g: 18,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'mussels_cooked_1',
    name: 'Mussels (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 172,
    protein_g: 24,
    carbs_g: 7,
    fat_g: 4.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 cup': 1.5 }
  },
  {
    food_id: 'oysters_raw_1',
    name: 'Oysters (Raw)',
    category: 'Protein',
    serving_size: '100g',
    calories: 81,
    protein_g: 9.5,
    carbs_g: 5,
    fat_g: 2.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '6 medium': 0.84 }
  },
  {
    food_id: 'pepperoni_1',
    name: 'Pepperoni',
    category: 'Protein',
    serving_size: '1 slice (2g)',
    calories: 10,
    protein_g: 0.4,
    carbs_g: 0,
    fat_g: 0.9,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 50 }
  },
  {
    food_id: 'prosciutto_1',
    name: 'Prosciutto',
    category: 'Protein',
    serving_size: '1 slice (7g)',
    calories: 25,
    protein_g: 1.8,
    carbs_g: 0,
    fat_g: 1.8,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 14.3 }
  },
  {
    food_id: 'salami_1',
    name: 'Salami',
    category: 'Protein',
    serving_size: '1 slice (10g)',
    calories: 40,
    protein_g: 2.2,
    carbs_g: 0.1,
    fat_g: 3.3,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 10 }
  },
  {
    food_id: 'sardines_canned_in_oil_1',
    name: 'Sardines (Canned in Oil)',
    category: 'Protein',
    serving_size: '100g',
    calories: 208,
    protein_g: 24.6,
    carbs_g: 0,
    fat_g: 11.2,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 can': 0.92 }
  },
  {
    food_id: 'tempeh_1',
    name: 'Tempeh',
    category: 'Protein',
    serving_size: '100g',
    calories: 193,
    protein_g: 19,
    carbs_g: 9,
    fat_g: 11,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 cup': 1.66 }
  },
  {
    food_id: 'venison_cooked_1',
    name: 'Venison (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 158,
    protein_g: 30,
    carbs_g: 0,
    fat_g: 3.2,
    fiber_g: 0,
    common_names: ['deer meat'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'amaranth_cooked_1',
    name: 'Amaranth (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 102,
    protein_g: 3.8,
    carbs_g: 18.7,
    fat_g: 1.6,
    fiber_g: 2.1,
    common_names: [],
    unit_conversions: { '1 cup': 2.46 }
  },
  {
    food_id: 'bulgur_cooked_1',
    name: 'Bulgur (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 83,
    protein_g: 3.1,
    carbs_g: 18.6,
    fat_g: 0.2,
    fiber_g: 4.5,
    common_names: [],
    unit_conversions: { '1 cup': 1.82 }
  },
  {
    food_id: 'cornbread_1',
    name: 'Cornbread',
    category: 'Carb',
    serving_size: '1 piece (60g)',
    calories: 173,
    protein_g: 3.8,
    carbs_g: 25,
    fat_g: 6,
    fiber_g: 1.8,
    common_names: [],
    unit_conversions: { '100g': 1.67 }
  },
  {
    food_id: 'croissant_1',
    name: 'Croissant',
    category: 'Carb',
    serving_size: '1 medium (57g)',
    calories: 231,
    protein_g: 4.6,
    carbs_g: 26,
    fat_g: 12,
    fiber_g: 1.5,
    common_names: [],
    unit_conversions: { '100g': 1.75 }
  },
  {
    food_id: 'french_fries_baked_1',
    name: 'French Fries (Baked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 130,
    protein_g: 2.5,
    carbs_g: 25,
    fat_g: 2.5,
    fiber_g: 2.2,
    common_names: ['oven chips'],
    unit_conversions: { '1 medium serving': 1.17 }
  },
  {
    food_id: 'gnocchi_potato_1',
    name: 'Gnocchi (Potato)',
    category: 'Carb',
    serving_size: '100g',
    calories: 168,
    protein_g: 3.8,
    carbs_g: 37,
    fat_g: 0.4,
    fiber_g: 2.3,
    common_names: [],
    unit_conversions: { '1 cup': 1.5 }
  },
  {
    food_id: 'millet_cooked_1',
    name: 'Millet (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 119,
    protein_g: 3.5,
    carbs_g: 23.7,
    fat_g: 1,
    fiber_g: 1.3,
    common_names: [],
    unit_conversions: { '1 cup': 1.74 }
  },
  {
    food_id: 'pancake_1',
    name: 'Pancake',
    category: 'Carb',
    serving_size: '1 pancake (4" dia)',
    calories: 74,
    protein_g: 2,
    carbs_g: 12,
    fat_g: 2,
    fiber_g: 0.5,
    common_names: [],
    unit_conversions: { '100g': 2.7 }
  },
  {
    food_id: 'polenta_cooked_1',
    name: 'Polenta (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 72,
    protein_g: 1.7,
    carbs_g: 15.5,
    fat_g: 0.4,
    fiber_g: 0.9,
    common_names: ['corn grits'],
    unit_conversions: { '1 cup': 2.42 }
  },
  {
    food_id: 'pumpernickel_bread_1',
    name: 'Pumpernickel Bread',
    category: 'Carb',
    serving_size: '1 slice (32g)',
    calories: 80,
    protein_g: 2.8,
    carbs_g: 15,
    fat_g: 1,
    fiber_g: 2.4,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'rice_noodles_cooked_1',
    name: 'Rice Noodles (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 109,
    protein_g: 1.8,
    carbs_g: 24,
    fat_g: 0.2,
    fiber_g: 0.9,
    common_names: [],
    unit_conversions: { '1 cup': 1.76 }
  },
  {
    food_id: 'sorghum_cooked_1',
    name: 'Sorghum (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 114,
    protein_g: 3.6,
    carbs_g: 25,
    fat_g: 1.1,
    fiber_g: 2.3,
    common_names: [],
    unit_conversions: { '1 cup': 1.92 }
  },
  {
    food_id: 'wild_rice_cooked_1',
    name: 'Wild Rice (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 101,
    protein_g: 4,
    carbs_g: 21,
    fat_g: 0.3,
    fiber_g: 1.8,
    common_names: [],
    unit_conversions: { '1 cup': 1.64 }
  },
  {
    food_id: 'avocado_oil_1',
    name: 'Avocado Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 124,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'brazil_nuts_1',
    name: 'Brazil Nuts',
    category: 'Fats',
    serving_size: '1 oz (28g)',
    calories: 187,
    protein_g: 4.1,
    carbs_g: 3.3,
    fat_g: 19,
    fiber_g: 2.1,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'hazelnuts_1',
    name: 'Hazelnuts',
    category: 'Fats',
    serving_size: '1 oz (28g)',
    calories: 178,
    protein_g: 4.2,
    carbs_g: 4.7,
    fat_g: 17,
    fiber_g: 2.7,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'lard_1',
    name: 'Lard',
    category: 'Fats',
    serving_size: '1 tbsp (13g)',
    calories: 115,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.69 }
  },
  {
    food_id: 'margarine_1',
    name: 'Margarine',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 101,
    protein_g: 0.1,
    carbs_g: 0.1,
    fat_g: 11.4,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'olives_green_canned_1',
    name: 'Olives (Green, Canned)',
    category: 'Fats',
    serving_size: '100g',
    calories: 145,
    protein_g: 1,
    carbs_g: 3.8,
    fat_g: 15,
    fiber_g: 3.3,
    common_names: [],
    unit_conversions: { '10 large': 0.4 }
  },
  {
    food_id: 'pine_nuts_1',
    name: 'Pine Nuts',
    category: 'Fats',
    serving_size: '1 oz (28g)',
    calories: 191,
    protein_g: 3.9,
    carbs_g: 3.7,
    fat_g: 19,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'coconut_shredded_unsweetened_1',
    name: 'Coconut (Shredded, Unsweetened)',
    category: 'Fats',
    serving_size: '100g',
    calories: 660,
    protein_g: 6.9,
    carbs_g: 24,
    fat_g: 65,
    fiber_g: 16.3,
    common_names: ['desiccated coconut'],
    unit_conversions: { '1 cup': 0.8 }
  },
  {
    food_id: 'cacao_nibs_1',
    name: 'Cacao Nibs',
    category: 'Fats',
    serving_size: '1 oz (28g)',
    calories: 160,
    protein_g: 4,
    carbs_g: 10,
    fat_g: 12,
    fiber_g: 9,
    common_names: [],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'flax_oil_1',
    name: 'Flax Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 124,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: ['linseed oil'],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'goji_berries_dried_1',
    name: 'Goji Berries (Dried)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 349,
    protein_g: 14.3,
    carbs_g: 77,
    fat_g: 0.4,
    fiber_g: 13,
    common_names: ['wolfberries'],
    unit_conversions: { '5 tbsp': 0.28 }
  },
  {
    food_id: 'jackfruit_raw_1',
    name: 'Jackfruit (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 95,
    protein_g: 1.7,
    carbs_g: 23,
    fat_g: 0.6,
    fiber_g: 1.5,
    common_names: [],
    unit_conversions: { '1 cup': 1.65 }
  },
  {
    food_id: 'kumquat_raw_1',
    name: 'Kumquat (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 71,
    protein_g: 1.9,
    carbs_g: 16,
    fat_g: 0.9,
    fiber_g: 6.5,
    common_names: [],
    unit_conversions: { '1 fruit': 0.19 }
  },
  {
    food_id: 'lychee_raw_1',
    name: 'Lychee (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 66,
    protein_g: 0.8,
    carbs_g: 17,
    fat_g: 0.4,
    fiber_g: 1.3,
    common_names: [],
    unit_conversions: { '1 cup': 1.9 }
  },
  {
    food_id: 'mulberries_raw_1',
    name: 'Mulberries (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 43,
    protein_g: 1.4,
    carbs_g: 10,
    fat_g: 0.4,
    fiber_g: 1.7,
    common_names: [],
    unit_conversions: { '1 cup': 1.4 }
  },
  {
    food_id: 'passion_fruit_raw_1',
    name: 'Passion Fruit (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 97,
    protein_g: 2.2,
    carbs_g: 23,
    fat_g: 0.7,
    fiber_g: 10.4,
    common_names: [],
    unit_conversions: { '1 fruit': 0.18 }
  },
  {
    food_id: 'persimmon_raw_1',
    name: 'Persimmon (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 70,
    protein_g: 0.6,
    carbs_g: 19,
    fat_g: 0.2,
    fiber_g: 3.6,
    common_names: [],
    unit_conversions: { '1 fruit': 1.68 }
  },
  {
    food_id: 'plantain_cooked_1',
    name: 'Plantain (Cooked)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 122,
    protein_g: 1.3,
    carbs_g: 32,
    fat_g: 0.4,
    fiber_g: 2.3,
    common_names: [],
    unit_conversions: { '1 cup': 1.54 }
  },
  {
    food_id: 'starfruit_raw_1',
    name: 'Starfruit (Raw)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 31,
    protein_g: 1,
    carbs_g: 6.7,
    fat_g: 0.3,
    fiber_g: 2.8,
    common_names: ['carambola'],
    unit_conversions: { '1 cup': 1.08 }
  },
  {
    food_id: 'bamboo_shoots_canned_1',
    name: 'Bamboo Shoots (Canned)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 19,
    protein_g: 1.5,
    carbs_g: 3,
    fat_g: 0.3,
    fiber_g: 1.7,
    common_names: [],
    unit_conversions: { '1 cup': 1.51 }
  },
  {
    food_id: 'bok_choy_cooked_1',
    name: 'Bok Choy (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 12,
    protein_g: 1.1,
    carbs_g: 2.4,
    fat_g: 0.2,
    fiber_g: 1.1,
    common_names: ['pak choi', 'chinese cabbage'],
    unit_conversions: { '1 cup': 1.7 }
  },
  {
    food_id: 'endive_raw_1',
    name: 'Endive (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 17,
    protein_g: 1.3,
    carbs_g: 3.4,
    fat_g: 0.2,
    fiber_g: 3.1,
    common_names: [],
    unit_conversions: { '1 head': 0.51 }
  },
  {
    food_id: 'fennel_raw_1',
    name: 'Fennel (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 31,
    protein_g: 1.2,
    carbs_g: 7,
    fat_g: 0.2,
    fiber_g: 3.1,
    common_names: [],
    unit_conversions: { '1 bulb': 2.34 }
  },
  {
    food_id: 'jicama_raw_1',
    name: 'Jicama (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 38,
    protein_g: 0.7,
    carbs_g: 8.8,
    fat_g: 0.1,
    fiber_g: 4.9,
    common_names: [],
    unit_conversions: { '1 cup': 1.2 }
  },
  {
    food_id: 'kohlrabi_raw_1',
    name: 'Kohlrabi (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 27,
    protein_g: 1.7,
    carbs_g: 6.2,
    fat_g: 0.1,
    fiber_g: 3.6,
    common_names: [],
    unit_conversions: { '1 cup': 1.35 }
  },
  {
    food_id: 'radicchio_raw_1',
    name: 'Radicchio (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 23,
    protein_g: 1.4,
    carbs_g: 4.5,
    fat_g: 0.3,
    fiber_g: 0.9,
    common_names: [],
    unit_conversions: { '1 cup': 0.4 }
  },
  {
    food_id: 'rutabaga_cooked_1',
    name: 'Rutabaga (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 30,
    protein_g: 1,
    carbs_g: 7,
    fat_g: 0.2,
    fiber_g: 1.8,
    common_names: ['swede'],
    unit_conversions: { '1 cup': 1.7 }
  },
  {
    food_id: 'seaweed_nori_dried_1',
    name: 'Seaweed (Nori, Dried)',
    category: 'Vegetable',
    serving_size: '1 sheet (2.6g)',
    calories: 9,
    protein_g: 1.5,
    carbs_g: 1.3,
    fat_g: 0.1,
    fiber_g: 0.1,
    common_names: [],
    unit_conversions: { '100g': 38.5 }
  },
  {
    food_id: 'spaghetti_squash_cooked_1',
    name: 'Spaghetti Squash (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 31,
    protein_g: 0.6,
    carbs_g: 7,
    fat_g: 0.6,
    fiber_g: 1.5,
    common_names: [],
    unit_conversions: { '1 cup': 1.55 }
  },
  {
    food_id: 'buttermilk_lowfat_1',
    name: 'Buttermilk (Low-fat)',
    category: 'Dairy',
    serving_size: '1 cup (245g)',
    calories: 98,
    protein_g: 8.1,
    carbs_g: 12,
    fat_g: 2.2,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 0.41 }
  },
  {
    food_id: 'heavy_cream_1',
    name: 'Heavy Cream',
    category: 'Dairy',
    serving_size: '1 tbsp (15g)',
    calories: 51,
    protein_g: 0.4,
    carbs_g: 0.4,
    fat_g: 5.4,
    fiber_g: 0,
    common_names: ['whipping cream'],
    unit_conversions: { '100g': 6.67 }
  },
  {
    food_id: 'goat_cheese_soft_1',
    name: 'Goat Cheese (Soft)',
    category: 'Dairy',
    serving_size: '1 oz (28g)',
    calories: 102,
    protein_g: 6.1,
    carbs_g: 0,
    fat_g: 8.5,
    fiber_g: 0,
    common_names: ['chevre'],
    unit_conversions: { '100g': 3.57 }
  },
  {
    food_id: 'ricotta_cheese_whole_milk_1',
    name: 'Ricotta Cheese (Whole Milk)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 174,
    protein_g: 11.3,
    carbs_g: 3,
    fat_g: 13,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 cup': 2.46 }
  },
  {
    food_id: 'rice_milk_1',
    name: 'Rice Milk',
    category: 'Dairy',
    serving_size: '1 cup (240ml)',
    calories: 120,
    protein_g: 0.7,
    carbs_g: 22,
    fat_g: 2.3,
    fiber_g: 0.7,
    common_names: [],
    unit_conversions: { '100ml': 0.416 }
  },
  {
    food_id: 'coconut_cream_canned_1',
    name: 'Coconut Cream (Canned)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 330,
    protein_g: 3.6,
    carbs_g: 6.7,
    fat_g: 35,
    fiber_g: 2.2,
    common_names: [],
    unit_conversions: { '1 tbsp': 0.15 }
  },
  {
    food_id: 'creme_fraiche_1',
    name: 'Creme Fraiche',
    category: 'Dairy',
    serving_size: '1 tbsp (15g)',
    calories: 42,
    protein_g: 0.4,
    carbs_g: 0.4,
    fat_g: 4.3,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 6.67 }
  },
  {
    food_id: 'club_soda_1',
    name: 'Club Soda',
    category: 'Beverage',
    serving_size: '12 oz (355ml)',
    calories: 0,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    common_names: ['soda water', 'sparkling water'],
    unit_conversions: {}
  },
  {
    food_id: 'cola_1',
    name: 'Cola',
    category: 'Beverage',
    serving_size: '12 oz (355ml)',
    calories: 139,
    protein_g: 0,
    carbs_g: 39,
    fat_g: 0,
    fiber_g: 0,
    common_names: ['coke', 'pepsi', 'soda pop'],
    unit_conversions: {}
  },
  {
    food_id: 'cranberry_juice_cocktail_1',
    name: 'Cranberry Juice Cocktail',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 137,
    protein_g: 0,
    carbs_g: 34,
    fat_g: 0.2,
    fiber_g: 0.2,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'energy_drink_1',
    name: 'Energy Drink',
    category: 'Beverage',
    serving_size: '8.4 oz (250ml)',
    calories: 110,
    protein_g: 0,
    carbs_g: 27,
    fat_g: 0,
    fiber_g: 0,
    common_names: ['red bull', 'monster'],
    unit_conversions: {}
  },
  {
    food_id: 'hot_chocolate_1',
    name: 'Hot Chocolate',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 192,
    protein_g: 8.5,
    carbs_g: 26,
    fat_g: 5,
    fiber_g: 2,
    common_names: ['hot cocoa'],
    unit_conversions: {}
  },
  {
    food_id: 'iced_tea_sweetened_1',
    name: 'Iced Tea (Sweetened)',
    category: 'Beverage',
    serving_size: '12 oz (355ml)',
    calories: 90,
    protein_g: 0,
    carbs_g: 24,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'lemonade_1',
    name: 'Lemonade',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 100,
    protein_g: 0,
    carbs_g: 27,
    fat_g: 0,
    fiber_g: 0.2,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'tomato_juice_1',
    name: 'Tomato Juice',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 41,
    protein_g: 1.7,
    carbs_g: 10,
    fat_g: 0.3,
    fiber_g: 1,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'gelatin_dessert_1',
    name: 'Gelatin Dessert',
    category: 'Misc',
    serving_size: '1/2 cup (117g)',
    calories: 84,
    protein_g: 1.6,
    carbs_g: 19,
    fat_g: 0,
    fiber_g: 0,
    common_names: ['jello'],
    unit_conversions: { '100g': 0.85 }
  },
  {
    food_id: 'ice_cream_vanilla_1',
    name: 'Ice Cream (Vanilla)',
    category: 'Snack',
    serving_size: '1/2 cup (66g)',
    calories: 137,
    protein_g: 2.3,
    carbs_g: 16,
    fat_g: 7,
    fiber_g: 0.7,
    common_names: [],
    unit_conversions: { '100g': 1.51 }
  },
  {
    food_id: 'jelly_jam_preserves_1',
    name: 'Jelly/Jam/Preserves',
    category: 'Misc',
    serving_size: '1 tbsp (20g)',
    calories: 56,
    protein_g: 0.1,
    carbs_g: 14,
    fat_g: 0,
    fiber_g: 0.2,
    common_names: ['jam', 'jelly', 'preserves'],
    unit_conversions: { '100g': 5 }
  },
  {
    food_id: 'pizza_cheese_1',
    name: 'Pizza (Cheese)',
    category: 'Snack',
    serving_size: '1 slice (107g)',
    calories: 285,
    protein_g: 12,
    carbs_g: 36,
    fat_g: 10,
    fiber_g: 2.5,
    common_names: [],
    unit_conversions: { '100g': 0.93 }
  },
  {
    food_id: 'pizza_pepperoni_1',
    name: 'Pizza (Pepperoni)',
    category: 'Snack',
    serving_size: '1 slice (111g)',
    calories: 313,
    protein_g: 13,
    carbs_g: 36,
    fat_g: 13,
    fiber_g: 2.5,
    common_names: [],
    unit_conversions: { '100g': 0.9 }
  },
  {
    food_id: 'pudding_chocolate_1',
    name: 'Pudding (Chocolate)',
    category: 'Snack',
    serving_size: '1/2 cup (124g)',
    calories: 140,
    protein_g: 2,
    carbs_g: 25,
    fat_g: 4,
    fiber_g: 1.5,
    common_names: [],
    unit_conversions: { '100g': 0.81 }
  },
  {
    food_id: 'sherbet_orange_1',
    name: 'Sherbet (Orange)',
    category: 'Snack',
    serving_size: '1/2 cup (96g)',
    calories: 144,
    protein_g: 1.1,
    carbs_g: 30,
    fat_g: 2,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 1.04 }
  },
  {
    food_id: 'teriyaki_sauce_1',
    name: 'Teriyaki Sauce',
    category: 'Misc',
    serving_size: '1 tbsp (18g)',
    calories: 15,
    protein_g: 0.8,
    carbs_g: 2.5,
    fat_g: 0,
    fiber_g: 0.1,
    common_names: [],
    unit_conversions: { '100g': 5.56 }
  },
  {
    food_id: 'vinegar_apple_cider_1',
    name: 'Vinegar (Apple Cider)',
    category: 'Misc',
    serving_size: '1 tbsp (15g)',
    calories: 3,
    protein_g: 0,
    carbs_g: 0.1,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 6.67 }
  },
  {
    food_id: 'yeast_nutritional_1',
    name: 'Yeast (Nutritional)',
    category: 'Misc',
    serving_size: '2 tbsp (16g)',
    calories: 60,
    protein_g: 8,
    carbs_g: 5,
    fat_g: 0.5,
    fiber_g: 4,
    common_names: ['nooch'],
    unit_conversions: { '100g': 6.25 }
  },
  // Steaks
  {
    food_id: 'steak_filet_mignon_broiled_0',
    name: 'Filet Mignon (Tenderloin Steak)',
    category: 'Protein',
    serving_size: '100g',
    calories: 270,
    protein_g: 28,
    carbs_g: 0,
    fat_g: 17,
    fiber_g: 0,
    common_names: ['tenderloin steak', 'filet', 'steak'],
    unit_conversions: { '3 oz': 0.85, '6 oz': 1.7 }
  },
  {
    food_id: 'steak_ribeye_broiled_0',
    name: 'Ribeye Steak (Boneless, Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 291,
    protein_g: 24,
    carbs_g: 0,
    fat_g: 21,
    fiber_g: 0,
    common_names: ['ribeye', 'delmonico steak', 'steak'],
    unit_conversions: { '10 oz': 2.83 }
  },
  {
    food_id: 'steak_ny_strip_broiled_0',
    name: 'New York Strip Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 224,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: ['ny strip', 'kansas city strip', 'striploin', 'steak'],
    unit_conversions: { '8 oz': 2.27 }
  },
  {
    food_id: 'steak_tbone_broiled_0',
    name: 'T-Bone Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 286,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 21,
    fiber_g: 0,
    common_names: ['t-bone', 'steak'],
    unit_conversions: { '1 steak (16oz)': 4.54 }
  },
  {
    food_id: 'steak_porterhouse_broiled_0',
    name: 'Porterhouse Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 290,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 22,
    fiber_g: 0,
    common_names: ['porterhouse', 'steak'],
    unit_conversions: { '1 steak (24oz)': 6.8 }
  },
  {
    food_id: 'steak_flank_broiled_0',
    name: 'Flank Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 212,
    protein_g: 28,
    carbs_g: 0,
    fat_g: 10,
    fiber_g: 0,
    common_names: ['flank steak', 'steak'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'steak_skirt_broiled_0',
    name: 'Skirt Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 255,
    protein_g: 27,
    carbs_g: 0,
    fat_g: 16,
    fiber_g: 0,
    common_names: ['skirt steak', 'steak'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'steak_hanger_broiled_0',
    name: 'Hanger Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 213,
    protein_g: 27,
    carbs_g: 0,
    fat_g: 11,
    fiber_g: 0,
    common_names: ['hanger steak', "butcher's steak", 'steak'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'steak_flatiron_broiled_0',
    name: 'Flat Iron Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 220,
    protein_g: 23,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: ['flat iron steak', 'steak'],
    unit_conversions: { '6 oz': 1.7 }
  },
// Ground Beef
  {
    food_id: 'ground_beef_70_30_pan_browned_0',
    name: 'Ground Beef (70/30, Pan-browned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 332,
    protein_g: 14,
    carbs_g: 0,
    fat_g: 30,
    fiber_g: 0,
    common_names: ['70% lean ground beef'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'ground_beef_75_25_pan_browned_0',
    name: 'Ground Beef (75/25, Pan-browned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 300,
    protein_g: 15,
    carbs_g: 0,
    fat_g: 26,
    fiber_g: 0,
    common_names: ['75% lean ground beef'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'ground_beef_80_20_pan_browned_0',
    name: 'Ground Beef (80/20, Pan-browned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 260,
    protein_g: 17,
    carbs_g: 0,
    fat_g: 20,
    fiber_g: 0,
    common_names: ['80% lean ground beef', 'ground chuck'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'ground_beef_85_15_pan_browned_0',
    name: 'Ground Beef (85/15, Pan-browned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 240,
    protein_g: 18,
    carbs_g: 0,
    fat_g: 17,
    fiber_g: 0,
    common_names: ['85% lean ground beef', 'ground round'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'ground_beef_90_10_0',
    name: 'Ground Beef (90/10, Pan-browned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 200,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    common_names: ['90% lean ground beef', 'ground sirloin', 'minced beef'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'ground_beef_95_5_pan_browned_0',
    name: 'Ground Beef (95/5, Pan-browned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 164,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 8,
    fiber_g: 0,
    common_names: ['95% lean ground beef', 'extra lean ground beef'],
    unit_conversions: { '4 oz': 1.13 }
  },
];
