
import type { FoodDBItem } from '@/types';

// This file contains the initial food data to be seeded into your Firestore database.
// You can add more food items to this array by following the same format.
// After adding data, go to the /nutrition page and click the "Seed Food Database" button.

export const foodDatabase: FoodDBItem[] = [
  // Proteins
  {
    food_id: 'chicken_breast_grilled_0',
    name: 'Chicken Breast (Grilled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 165,
    protein_g: 31,
    carbs_g: 0,
    fat_g: 3.6,
    fiber_g: 0,
    common_names: [ 'grilled chicken', 'chicken breast' ],
    unit_conversions: { '1 piece (120g)': 1.2, '1 oz': 0.28 }
  },
  {
    food_id: 'salmon_baked_0',
    name: 'Salmon (Baked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 206,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    common_names: ['baked salmon', 'salmon fillet'],
    unit_conversions: { '3 oz fillet': 0.85 }
  },
  {
    food_id: 'ground_beef_90_10_0',
    name: 'Ground Beef (90/10)',
    category: 'Protein',
    serving_size: '100g',
    calories: 200,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    common_names: ['lean ground beef', 'minced beef'],
    unit_conversions: { '4 oz': 1.13 }
  },
  {
    food_id: 'whole_egg_0',
    name: 'Egg (Large)',
    category: 'Protein',
    serving_size: '1 egg',
    calories: 72,
    protein_g: 6.3,
    carbs_g: 0.4,
    fat_g: 4.8,
    fiber_g: 0,
    common_names: [ 'egg', 'whole egg' ],
    unit_conversions: { '100g': 2 }
  },
  {
    food_id: 'tofu_firm_0',
    name: 'Tofu (Firm)',
    category: 'Protein',
    serving_size: '100g',
    calories: 76,
    protein_g: 8,
    carbs_g: 1.9,
    fat_g: 4.8,
    fiber_g: 1.9,
    common_names: ['bean curd'],
    unit_conversions: { '1 cup': 2.5 }
  },
  {
    food_id: 'lentils_cooked_0',
    name: 'Lentils (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 116,
    protein_g: 9,
    carbs_g: 20,
    fat_g: 0.4,
    fiber_g: 8,
    common_names: ['lentil soup base'],
    unit_conversions: { '1 cup': 1.98 }
  },
  {
    food_id: 'chickpeas_canned_0',
    name: 'Chickpeas (Canned)',
    category: 'Protein',
    serving_size: '100g',
    calories: 139,
    protein_g: 8.9,
    carbs_g: 27.4,
    fat_g: 2.6,
    fiber_g: 7.6,
    common_names: ['garbanzo beans'],
    unit_conversions: { '1 cup': 2.4 }
  },
  {
    food_id: 'greek_yogurt_plain_0',
    name: 'Greek Yogurt (Plain, Non-fat)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 59,
    protein_g: 10,
    carbs_g: 3.6,
    fat_g: 0.4,
    fiber_g: 0,
    common_names: ['strained yogurt'],
    unit_conversions: { '1 cup': 2.24 }
  },
  {
    food_id: 'cottage_cheese_2_0',
    name: 'Cottage Cheese (2%)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 81,
    protein_g: 12.4,
    carbs_g: 4.1,
    fat_g: 2.3,
    fiber_g: 0,
    common_names: ['curds and whey'],
    unit_conversions: { '1 cup': 2.26 }
  },
  {
    food_id: 'tuna_canned_in_water_0',
    name: 'Tuna (Canned in Water)',
    category: 'Protein',
    serving_size: '100g',
    calories: 116,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 0.8,
    fiber_g: 0,
    common_names: ['canned tuna'],
    unit_conversions: { '1 can (5 oz)': 1.42 }
  },
  {
    food_id: 'whey_protein_powder_0',
    name: 'Whey Protein Powder',
    category: 'Supplements',
    serving_size: '1 scoop (30g)',
    calories: 120,
    protein_g: 24,
    carbs_g: 3,
    fat_g: 1,
    fiber_g: 1,
    common_names: ['protein shake'],
    unit_conversions: { '100g': 3.33 }
  },
  {
    food_id: 'shrimp_cooked_0',
    name: 'Shrimp (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 99,
    protein_g: 24,
    carbs_g: 0.2,
    fat_g: 0.3,
    fiber_g: 0,
    common_names: ['prawns'],
    unit_conversions: { '3 oz': 0.85 }
  },

  // Carbohydrates
  {
    food_id: 'white_rice_cooked_0',
    name: 'White Rice (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 130,
    protein_g: 2.4,
    carbs_g: 28,
    fat_g: 0.3,
    fiber_g: 0.4,
    common_names: [ 'white rice' ],
    unit_conversions: { '1 cup': 1.58 }
  },
  {
    food_id: 'brown_rice_cooked_0',
    name: 'Brown Rice (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 111,
    protein_g: 2.6,
    carbs_g: 23,
    fat_g: 0.9,
    fiber_g: 1.8,
    common_names: ['whole grain rice'],
    unit_conversions: { '1 cup': 1.95 }
  },
  {
    food_id: 'quinoa_cooked_0',
    name: 'Quinoa (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 120,
    protein_g: 4.4,
    carbs_g: 21,
    fat_g: 1.9,
    fiber_g: 2.8,
    common_names: [],
    unit_conversions: { '1 cup': 1.85 }
  },
  {
    food_id: 'oats_rolled_dry_0',
    name: 'Oats (Rolled, Dry)',
    category: 'Carb',
    serving_size: '100g',
    calories: 389,
    protein_g: 16.9,
    carbs_g: 66.3,
    fat_g: 6.9,
    fiber_g: 10.6,
    common_names: ['oatmeal'],
    unit_conversions: { '1 cup (81g)': 0.81 }
  },
  {
    food_id: 'whole_wheat_bread_0',
    name: 'Whole Wheat Bread',
    category: 'Carb',
    serving_size: '1 slice (32g)',
    calories: 81,
    protein_g: 3.9,
    carbs_g: 13.8,
    fat_g: 1.1,
    fiber_g: 1.9,
    common_names: ['brown bread'],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'sweet_potato_baked_0',
    name: 'Sweet Potato (Baked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 90,
    protein_g: 2,
    carbs_g: 21,
    fat_g: 0.2,
    fiber_g: 3.3,
    common_names: ['yams'],
    unit_conversions: { '1 medium (114g)': 1.14 }
  },
  {
    food_id: 'russet_potato_baked_0',
    name: 'Russet Potato (Baked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 93,
    protein_g: 2.5,
    carbs_g: 21.2,
    fat_g: 0.1,
    fiber_g: 2.2,
    common_names: ['white potato'],
    unit_conversions: { '1 medium (173g)': 1.73 }
  },
  {
    food_id: 'pasta_cooked_0',
    name: 'Pasta (Cooked)',
    category: 'Carb',
    serving_size: '100g',
    calories: 131,
    protein_g: 5,
    carbs_g: 25,
    fat_g: 1.1,
    fiber_g: 1.8,
    common_names: ['spaghetti', 'macaroni'],
    unit_conversions: { '1 cup': 1.4 }
  },
  {
    food_id: 'sourdough_bread_0',
    name: 'Sourdough Bread',
    category: 'Carb',
    serving_size: '1 slice (32g)',
    calories: 90,
    protein_g: 3.8,
    carbs_g: 18.2,
    fat_g: 0.6,
    fiber_g: 0.9,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'bagel_plain_0',
    name: 'Bagel (Plain)',
    category: 'Carb',
    serving_size: '1 medium (99g)',
    calories: 250,
    protein_g: 10,
    carbs_g: 50,
    fat_g: 1.5,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100g': 1.01 }
  },
  {
    food_id: 'corn_tortilla_0',
    name: 'Corn Tortilla',
    category: 'Carb',
    serving_size: '1 tortilla (24g)',
    calories: 52,
    protein_g: 1.4,
    carbs_g: 11,
    fat_g: 0.6,
    fiber_g: 1.3,
    common_names: [],
    unit_conversions: { '100g': 4.16 }
  },

  // Fats
  {
    food_id: 'avocado_0',
    name: 'Avocado',
    category: 'Fats',
    serving_size: '100g',
    calories: 160,
    protein_g: 2,
    carbs_g: 8.5,
    fat_g: 14.7,
    fiber_g: 6.7,
    common_names: [],
    unit_conversions: { '1 medium (200g)': 2 }
  },
  {
    food_id: 'olive_oil_0',
    name: 'Olive Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 119,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.5,
    fiber_g: 0,
    common_names: ['extra virgin olive oil'],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'almonds_raw_0',
    name: 'Almonds (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 579,
    protein_g: 21.1,
    carbs_g: 21.6,
    fat_g: 49.9,
    fiber_g: 12.5,
    common_names: ['raw almonds'],
    unit_conversions: { '1 oz (28g)': 0.28 }
  },
  {
    food_id: 'peanut_butter_smooth_0',
    name: 'Peanut Butter (Smooth)',
    category: 'Fats',
    serving_size: '2 tbsp (32g)',
    calories: 191,
    protein_g: 7.2,
    carbs_g: 7.1,
    fat_g: 16,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '100g': 3.125 }
  },
  {
    food_id: 'walnuts_raw_0',
    name: 'Walnuts (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 654,
    protein_g: 15.2,
    carbs_g: 13.7,
    fat_g: 65.2,
    fiber_g: 6.7,
    common_names: [],
    unit_conversions: { '1 oz (28g)': 0.28 }
  },
  {
    food_id: 'chia_seeds_0',
    name: 'Chia Seeds',
    category: 'Fats',
    serving_size: '100g',
    calories: 486,
    protein_g: 16.5,
    carbs_g: 42.1,
    fat_g: 30.7,
    fiber_g: 34.4,
    common_names: [],
    unit_conversions: { '1 tbsp (12g)': 0.12 }
  },
  {
    food_id: 'cheddar_cheese_0',
    name: 'Cheddar Cheese',
    category: 'Fats',
    serving_size: '100g',
    calories: 404,
    protein_g: 25,
    carbs_g: 1.3,
    fat_g: 33,
    fiber_g: 0,
    common_names: ['cheddar'],
    unit_conversions: { '1 slice (28g)': 0.28 }
  },
  {
    food_id: 'cashews_raw_0',
    name: 'Cashews (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 553,
    protein_g: 18,
    carbs_g: 30,
    fat_g: 44,
    fiber_g: 3.3,
    common_names: [],
    unit_conversions: { '1 oz (28g)': 0.28 }
  },

  // Fruits
  {
    food_id: 'apple_0',
    name: 'Apple',
    category: 'Fruit',
    serving_size: '1 medium (182g)',
    calories: 95,
    protein_g: 0.5,
    carbs_g: 25,
    fat_g: 0.3,
    fiber_g: 4.4,
    common_names: ['gala apple', 'fuji apple'],
    unit_conversions: { '100g': 0.55 }
  },
  {
    food_id: 'banana_0',
    name: 'Banana',
    category: 'Fruit',
    serving_size: '1 medium (118g)',
    calories: 105,
    protein_g: 1.3,
    carbs_g: 27,
    fat_g: 0.4,
    fiber_g: 3.1,
    common_names: [],
    unit_conversions: { '100g': 0.85 }
  },
  {
    food_id: 'orange_0',
    name: 'Orange',
    category: 'Fruit',
    serving_size: '1 medium (131g)',
    calories: 62,
    protein_g: 1.2,
    carbs_g: 15.4,
    fat_g: 0.2,
    fiber_g: 3.1,
    common_names: ['navel orange'],
    unit_conversions: { '100g': 0.76 }
  },
  {
    food_id: 'strawberries_0',
    name: 'Strawberries',
    category: 'Fruit',
    serving_size: '100g',
    calories: 32,
    protein_g: 0.7,
    carbs_g: 7.7,
    fat_g: 0.3,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '1 cup': 1.52 }
  },
  {
    food_id: 'blueberries_0',
    name: 'Blueberries',
    category: 'Fruit',
    serving_size: '100g',
    calories: 57,
    protein_g: 0.7,
    carbs_g: 14.5,
    fat_g: 0.3,
    fiber_g: 2.4,
    common_names: [],
    unit_conversions: { '1 cup': 1.48 }
  },
  {
    food_id: 'grapes_0',
    name: 'Grapes',
    category: 'Fruit',
    serving_size: '100g',
    calories: 69,
    protein_g: 0.7,
    carbs_g: 18,
    fat_g: 0.2,
    fiber_g: 0.9,
    common_names: [],
    unit_conversions: { '1 cup': 1.51 }
  },
  {
    food_id: 'watermelon_0',
    name: 'Watermelon',
    category: 'Fruit',
    serving_size: '100g',
    calories: 30,
    protein_g: 0.6,
    carbs_g: 7.6,
    fat_g: 0.2,
    fiber_g: 0.4,
    common_names: [],
    unit_conversions: { '1 cup diced': 1.52 }
  },
  {
    food_id: 'pineapple_0',
    name: 'Pineapple',
    category: 'Fruit',
    serving_size: '100g',
    calories: 50,
    protein_g: 0.5,
    carbs_g: 13,
    fat_g: 0.1,
    fiber_g: 1.4,
    common_names: [],
    unit_conversions: { '1 cup chunks': 1.65 }
  },
  {
    food_id: 'mango_0',
    name: 'Mango',
    category: 'Fruit',
    serving_size: '100g',
    calories: 60,
    protein_g: 0.8,
    carbs_g: 15,
    fat_g: 0.4,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '1 cup sliced': 1.65 }
  },
  {
    food_id: 'raspberries_0',
    name: 'Raspberries',
    category: 'Fruit',
    serving_size: '100g',
    calories: 52,
    protein_g: 1.2,
    carbs_g: 12,
    fat_g: 0.7,
    fiber_g: 6.5,
    common_names: [],
    unit_conversions: { '1 cup': 1.23 }
  },

  // Vegetables
  {
    food_id: 'broccoli_steamed_0',
    name: 'Broccoli (Steamed)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 35,
    protein_g: 2.4,
    carbs_g: 7,
    fat_g: 0.4,
    fiber_g: 3.3,
    common_names: [ 'broccoli' ],
    unit_conversions: { '1 cup': 1.56 }
  },
  {
    food_id: 'spinach_raw_0',
    name: 'Spinach (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 23,
    protein_g: 2.9,
    carbs_g: 3.6,
    fat_g: 0.4,
    fiber_g: 2.2,
    common_names: [],
    unit_conversions: { '1 cup': 0.3 }
  },
  {
    food_id: 'carrots_raw_0',
    name: 'Carrots (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 41,
    protein_g: 0.9,
    carbs_g: 9.6,
    fat_g: 0.2,
    fiber_g: 2.8,
    common_names: [],
    unit_conversions: { '1 medium': 0.61 }
  },
  {
    food_id: 'bell_pepper_red_0',
    name: 'Bell Pepper (Red)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 31,
    protein_g: 1,
    carbs_g: 6,
    fat_g: 0.3,
    fiber_g: 2.1,
    common_names: ['red pepper', 'capsicum'],
    unit_conversions: { '1 medium': 1.19 }
  },
  {
    food_id: 'cucumber_0',
    name: 'Cucumber',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 15,
    protein_g: 0.7,
    carbs_g: 3.6,
    fat_g: 0.1,
    fiber_g: 0.5,
    common_names: [],
    unit_conversions: { '1 cup sliced': 1.04 }
  },
  {
    food_id: 'tomato_0',
    name: 'Tomato',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 18,
    protein_g: 0.9,
    carbs_g: 3.9,
    fat_g: 0.2,
    fiber_g: 1.2,
    common_names: [],
    unit_conversions: { '1 medium': 1.23 }
  },
  {
    food_id: 'lettuce_romaine_0',
    name: 'Lettuce (Romaine)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 17,
    protein_g: 1.2,
    carbs_g: 3.3,
    fat_g: 0.3,
    fiber_g: 2.1,
    common_names: ['romaine'],
    unit_conversions: { '1 cup shredded': 0.47 }
  },
  {
    food_id: 'onion_yellow_0',
    name: 'Onion (Yellow)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 40,
    protein_g: 1.1,
    carbs_g: 9.3,
    fat_g: 0.1,
    fiber_g: 1.7,
    common_names: ['onion'],
    unit_conversions: { '1 cup chopped': 1.6 }
  },
  {
    food_id: 'mushrooms_white_0',
    name: 'Mushrooms (White)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 22,
    protein_g: 3.1,
    carbs_g: 3.3,
    fat_g: 0.3,
    fiber_g: 1,
    common_names: ['button mushrooms'],
    unit_conversions: { '1 cup sliced': 0.96 }
  },
  {
    food_id: 'zucchini_0',
    name: 'Zucchini',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 17,
    protein_g: 1.2,
    carbs_g: 3.1,
    fat_g: 0.3,
    fiber_g: 1,
    common_names: ['courgette'],
    unit_conversions: { '1 cup sliced': 1.13 }
  },
  {
    food_id: 'garlic_0',
    name: 'Garlic',
    category: 'Vegetable',
    serving_size: '1 clove (3g)',
    calories: 5,
    protein_g: 0.2,
    carbs_g: 1,
    fat_g: 0,
    fiber_g: 0.1,
    common_names: [],
    unit_conversions: { '100g': 33.3 }
  },
  {
    food_id: 'kale_raw_0',
    name: 'Kale (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 49,
    protein_g: 4.3,
    carbs_g: 9,
    fat_g: 0.9,
    fiber_g: 3.6,
    common_names: [],
    unit_conversions: { '1 cup chopped': 0.67 }
  },
  {
    food_id: 'celery_raw_0',
    name: 'Celery (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 16,
    protein_g: 0.7,
    carbs_g: 3,
    fat_g: 0.2,
    fiber_g: 1.6,
    common_names: [],
    unit_conversions: { '1 cup chopped': 1.01 }
  },

  // Dairy & Alternatives
  {
    food_id: 'milk_whole_0',
    name: 'Milk (Whole, 3.25%)',
    category: 'Dairy',
    serving_size: '1 cup (244g)',
    calories: 149,
    protein_g: 7.7,
    carbs_g: 11.7,
    fat_g: 8,
    fiber_g: 0,
    common_names: ['whole milk'],
    unit_conversions: { '100g': 0.41 }
  },
  {
    food_id: 'milk_skim_0',
    name: 'Milk (Skim)',
    category: 'Dairy',
    serving_size: '1 cup (245g)',
    calories: 83,
    protein_g: 8.3,
    carbs_g: 12.2,
    fat_g: 0.2,
    fiber_g: 0,
    common_names: ['non-fat milk'],
    unit_conversions: { '100g': 0.408 }
  },
  {
    food_id: 'almond_milk_unsweetened_0',
    name: 'Almond Milk (Unsweetened)',
    category: 'Dairy',
    serving_size: '1 cup (240ml)',
    calories: 30,
    protein_g: 1,
    carbs_g: 1,
    fat_g: 2.5,
    fiber_g: 1,
    common_names: [],
    unit_conversions: { '100ml': 0.416 }
  },
  {
    food_id: 'soy_milk_unsweetened_0',
    name: 'Soy Milk (Unsweetened)',
    category: 'Dairy',
    serving_size: '1 cup (240ml)',
    calories: 80,
    protein_g: 7,
    carbs_g: 4,
    fat_g: 4,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '100ml': 0.416 }
  },
  {
    food_id: 'mozzarella_cheese_0',
    name: 'Mozzarella Cheese (Part-Skim)',
    category: 'Dairy',
    serving_size: '100g',
    calories: 280,
    protein_g: 28,
    carbs_g: 3.1,
    fat_g: 17,
    fiber_g: 0,
    common_names: ['mozzarella'],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'butter_salted_0',
    name: 'Butter (Salted)',
    category: 'Dairy',
    serving_size: '1 tbsp (14g)',
    calories: 102,
    protein_g: 0.1,
    carbs_g: 0,
    fat_g: 11.5,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },

  // Beverages
  {
    food_id: 'coffee_black_0',
    name: 'Coffee (Black)',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 2,
    protein_g: 0.3,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    common_names: ['black coffee'],
    unit_conversions: {}
  },
  {
    food_id: 'green_tea_0',
    name: 'Green Tea (Unsweetened)',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 2,
    protein_g: 0.5,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'orange_juice_0',
    name: 'Orange Juice',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 112,
    protein_g: 1.7,
    carbs_g: 26,
    fat_g: 0.5,
    fiber_g: 0.7,
    common_names: [],
    unit_conversions: {}
  },
  {
    food_id: 'apple_juice_0',
    name: 'Apple Juice',
    category: 'Beverage',
    serving_size: '1 cup (240ml)',
    calories: 114,
    protein_g: 0.2,
    carbs_g: 28,
    fat_g: 0.3,
    fiber_g: 0.5,
    common_names: [],
    unit_conversions: {}
  },
  
  // Miscellaneous
  {
    food_id: 'honey_0',
    name: 'Honey',
    category: 'Misc',
    serving_size: '1 tbsp (21g)',
    calories: 64,
    protein_g: 0.1,
    carbs_g: 17.3,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 4.76 }
  },
  {
    food_id: 'dark_chocolate_70_85_0',
    name: 'Dark Chocolate (70-85%)',
    category: 'Misc',
    serving_size: '100g',
    calories: 598,
    protein_g: 7.8,
    carbs_g: 45.9,
    fat_g: 42.6,
    fiber_g: 10.9,
    common_names: [],
    unit_conversions: { '1 square (10g)': 0.1 }
  },
  {
    food_id: 'ketchup_0',
    name: 'Ketchup',
    category: 'Misc',
    serving_size: '1 tbsp (17g)',
    calories: 17,
    protein_g: 0.2,
    carbs_g: 4.5,
    fat_g: 0.1,
    fiber_g: 0.1,
    common_names: ['tomato sauce'],
    unit_conversions: { '100g': 5.88 }
  },
  {
    food_id: 'mustard_yellow_0',
    name: 'Mustard (Yellow)',
    category: 'Misc',
    serving_size: '1 tsp (5g)',
    calories: 3,
    protein_g: 0.2,
    carbs_g: 0.3,
    fat_g: 0.2,
    fiber_g: 0.2,
    common_names: [],
    unit_conversions: { '100g': 20 }
  },
  {
    food_id: 'mayonnaise_full_fat_0',
    name: 'Mayonnaise (Full Fat)',
    category: 'Misc',
    serving_size: '1 tbsp (14g)',
    calories: 99,
    protein_g: 0.1,
    carbs_g: 0.1,
    fat_g: 11,
    fiber_g: 0,
    common_names: ['mayo'],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'popcorn_air_popped_0',
    name: 'Popcorn (Air-Popped)',
    category: 'Snack',
    serving_size: '1 cup (8g)',
    calories: 31,
    protein_g: 1,
    carbs_g: 6.2,
    fat_g: 0.4,
    fiber_g: 1.2,
    common_names: [],
    unit_conversions: { '100g': 12.5 }
  },
  {
    food_id: 'rice_cakes_brown_rice_0',
    name: 'Rice Cakes (Brown Rice)',
    category: 'Snack',
    serving_size: '1 cake (9g)',
    calories: 35,
    protein_g: 0.7,
    carbs_g: 7.3,
    fat_g: 0.3,
    fiber_g: 0.3,
    common_names: [],
    unit_conversions: { '100g': 11.1 }
  },
  {
    food_id: 'white_bread_0',
    name: 'White Bread',
    category: 'Carb',
    serving_size: '1 slice (25g)',
    calories: 66,
    protein_g: 2.3,
    carbs_g: 12.3,
    fat_g: 0.8,
    fiber_g: 0.6,
    common_names: [],
    unit_conversions: { '100g': 4 }
  },
  {
    food_id: 'turkey_breast_roasted_0',
    name: 'Turkey Breast (Roasted)',
    category: 'Protein',
    serving_size: '100g',
    calories: 135,
    protein_g: 30,
    carbs_g: 0,
    fat_g: 0.7,
    fiber_g: 0,
    common_names: ['roast turkey'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'sirloin_steak_broiled_0',
    name: 'Sirloin Steak (Broiled)',
    category: 'Protein',
    serving_size: '100g',
    calories: 206,
    protein_g: 29,
    carbs_g: 0,
    fat_g: 9,
    fiber_g: 0,
    common_names: ['beef sirloin'],
    unit_conversions: { '3 oz': 0.85 }
  },
  {
    food_id: 'pork_chop_cooked_0',
    name: 'Pork Chop (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 231,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '1 medium': 1.5 }
  },
  {
    food_id: 'black_beans_cooked_0',
    name: 'Black Beans (Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 132,
    protein_g: 8.9,
    carbs_g: 23.7,
    fat_g: 0.5,
    fiber_g: 8.7,
    common_names: [],
    unit_conversions: { '1 cup': 1.72 }
  },
  {
    food_id: 'edamame_shelled_cooked_0',
    name: 'Edamame (Shelled, Cooked)',
    category: 'Protein',
    serving_size: '100g',
    calories: 122,
    protein_g: 11,
    carbs_g: 10,
    fat_g: 5,
    fiber_g: 5,
    common_names: ['soybeans'],
    unit_conversions: { '1 cup': 1.55 }
  },
  {
    food_id: 'green_beans_cooked_0',
    name: 'Green Beans (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 35,
    protein_g: 1.8,
    carbs_g: 8,
    fat_g: 0.3,
    fiber_g: 3.2,
    common_names: [],
    unit_conversions: { '1 cup': 1.25 }
  },
  {
    food_id: 'asparagus_cooked_0',
    name: 'Asparagus (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 20,
    protein_g: 2.2,
    carbs_g: 3.9,
    fat_g: 0.1,
    fiber_g: 2.1,
    common_names: [],
    unit_conversions: { '1 cup': 1.8 }
  },
  {
    food_id: 'cauliflower_raw_0',
    name: 'Cauliflower (Raw)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 25,
    protein_g: 1.9,
    carbs_g: 5,
    fat_g: 0.3,
    fiber_g: 2,
    common_names: [],
    unit_conversions: { '1 cup': 1 }
  },
  {
    food_id: 'sweet_corn_cooked_0',
    name: 'Sweet Corn (Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 86,
    protein_g: 3.2,
    carbs_g: 19,
    fat_g: 1.2,
    fiber_g: 2.7,
    common_names: ['corn on the cob'],
    unit_conversions: { '1 ear': 1.4 }
  },
  {
    food_id: 'peas_green_cooked_0',
    name: 'Peas (Green, Cooked)',
    category: 'Vegetable',
    serving_size: '100g',
    calories: 81,
    protein_g: 5.4,
    carbs_g: 14.5,
    fat_g: 0.4,
    fiber_g: 5.1,
    common_names: ['green peas'],
    unit_conversions: { '1 cup': 1.6 }
  },
  {
    food_id: 'peach_0',
    name: 'Peach',
    category: 'Fruit',
    serving_size: '1 medium (150g)',
    calories: 59,
    protein_g: 1.4,
    carbs_g: 15,
    fat_g: 0.4,
    fiber_g: 2.3,
    common_names: [],
    unit_conversions: { '100g': 0.66 }
  },
  {
    food_id: 'pear_0',
    name: 'Pear',
    category: 'Fruit',
    serving_size: '1 medium (178g)',
    calories: 101,
    protein_g: 0.6,
    carbs_g: 27,
    fat_g: 0.2,
    fiber_g: 5.5,
    common_names: [],
    unit_conversions: { '100g': 0.56 }
  },
  {
    food_id: 'cherries_sweet_0',
    name: 'Cherries (Sweet)',
    category: 'Fruit',
    serving_size: '100g',
    calories: 63,
    protein_g: 1.1,
    carbs_g: 16,
    fat_g: 0.2,
    fiber_g: 2.1,
    common_names: [],
    unit_conversions: { '1 cup': 1.54 }
  },
  {
    food_id: 'kiwi_0',
    name: 'Kiwi',
    category: 'Fruit',
    serving_size: '1 medium (69g)',
    calories: 42,
    protein_g: 0.8,
    carbs_g: 10.1,
    fat_g: 0.4,
    fiber_g: 2.1,
    common_names: ['kiwifruit'],
    unit_conversions: { '100g': 1.45 }
  },
  {
    food_id: 'peanuts_raw_0',
    name: 'Peanuts (Raw)',
    category: 'Fats',
    serving_size: '100g',
    calories: 567,
    protein_g: 25.8,
    carbs_g: 16.1,
    fat_g: 49.2,
    fiber_g: 8.5,
    common_names: [],
    unit_conversions: { '1 oz': 0.28 }
  },
  {
    food_id: 'sunflower_seeds_0',
    name: 'Sunflower Seeds',
    category: 'Fats',
    serving_size: '100g',
    calories: 584,
    protein_g: 20.8,
    carbs_g: 20,
    fat_g: 51.5,
    fiber_g: 8.6,
    common_names: [],
    unit_conversions: { '1/4 cup': 0.3 }
  },
  {
    food_id: 'flax_seeds_ground_0',
    name: 'Flax Seeds (Ground)',
    category: 'Fats',
    serving_size: '1 tbsp (7g)',
    calories: 37,
    protein_g: 1.3,
    carbs_g: 2,
    fat_g: 3,
    fiber_g: 1.9,
    common_names: [],
    unit_conversions: { '100g': 14.3 }
  },
  {
    food_id: 'sesame_oil_0',
    name: 'Sesame Oil',
    category: 'Fats',
    serving_size: '1 tbsp (14g)',
    calories: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.6,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 7.14 }
  },
  {
    food_id: 'maple_syrup_0',
    name: 'Maple Syrup',
    category: 'Misc',
    serving_size: '1 tbsp (20g)',
    calories: 52,
    protein_g: 0,
    carbs_g: 13.4,
    fat_g: 0,
    fiber_g: 0,
    common_names: [],
    unit_conversions: { '100g': 5 }
  }
];
